# Dataset — tripadvisor_european_restaurants
(679.68 MB, 1 file, 42 columns, 5774 downloads, Updated 5 years ago)


https://www.kaggle.com/datasets/stefanoleone992/tripadvisor-european-restaurants

In [9]:
import pandas as pd
import numpy as np
import pyarrow
from IPython.display import display
import folium
from folium.plugins import MarkerCluster

# 1. Charger les données

In [10]:
#lire CSV_PATH (première fois)
CSV_PATH = "df_tripadvisor_france.csv"
df_trip_eu = pd.read_csv(CSV_PATH, sep=',', encoding='utf-8', low_memory = False)

#Convertir en Parquet --> Fichier beaucoup plus léger --> Lecture rapide
PARQUET_PATH = "df_tripadvisor_france.parquet"
df_trip_eu.to_parquet(PARQUET_PATH, compression = "snappy")

#Libère la mémoire et recharger le parquet
del df_trip_eu
df_trip_eu = pd.read_parquet("df_tripadvisor_france.parquet")

#Afficher 2 lignes et TOUTES les colonnes
pd.set_option("display.max_columns", None)
display(df_trip_eu.head(2))

print("\n-------------------------------------")
print("Nombre de lignes et de colones")
print(df_trip_eu.shape)

print("\n-------------------------------------")
print("Display info sur les colonnes et datatype")
display(df_trip_eu.info())

print("\n-------------------------------------")
print("Lister + count les pays de la colonne country")
display(df_trip_eu["country"].value_counts())

print("\n-------------------------------------")
print("Lister + count les régions en France")
display(df_trip_eu.loc[df_trip_eu["country"] == "France", "region"].value_counts())

,restaurant_link,restaurant_name,original_location,country,region,province,city,address,latitude,longitude,claimed,awards,popularity_detailed,popularity_generic,top_tags,price_level,price_range,meals,cuisines,special_diets,features,vegetarian_friendly,vegan_options,gluten_free,original_open_hours,open_days_per_week,open_hours_per_week,working_shifts_per_week,avg_rating,total_reviews_count,default_language,reviews_count_in_default_language,excellent,very_good,average,poor,terrible,food,service,value,atmosphere,keywords
0,g10001637-d10002227,Le 147,"[""Europe"", ""France"", ""Nouvelle-Aquitaine"", ""Ha...",France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,"10 Maison Neuve, 87510 Saint-Jouvent France",45.961674,1.169131,Claimed,None,#1 of 2 Restaurants in Saint-Jouvent,#1 of 2 places to eat in Saint-Jouvent,"Cheap Eats, French",€,None,"Lunch, Dinner",French,None,"Reservations, Seating, Wheelchair Accessible, ...",N,N,N,None,NaN,NaN,NaN,4.0,36.0,English,2.0,2.0,0.0,0.0,0.0,0.0,4.0,4.5,4.0,NaN,None
1,g10001637-d14975787,Le Saint Jouvent,"[""Europe"", ""France"", ""Nouvelle-Aquitaine"", ""Ha...",France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,"16 Place de l Eglise, 87510 Saint-Jouvent France",45.957040,1.205480,Unclaimed,None,#2 of 2 Restaurants in Saint-Jouvent,#2 of 2 places to eat in Saint-Jouvent,Cheap Eats,€,None,None,None,None,None,N,N,N,None,NaN,NaN,NaN,4.0,5.0,All languages,5.0,2.0,2.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,None

-------------------------------------
Nombre de lignes et de colones
(1083397, 42)

-------------------------------------
Display info sur les colonnes et datatype
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1083397 entries, 0 to 1083396
Data columns (total 42 columns):
 #   Column                             Non-Null Count    Dtype
---  ------                             --------------    -----
 0   restaurant_link                    1083397 non-null  object
 1   restaurant_name                    1083396 non-null  object
 2   original_location                  1083397 non-null  object
 3   country                            1083397 non-null  object
 4   region                             1033074 non-null  object
 5   province                           742765 non-null   object
 6   city                               682712 non-null   object
 7   address                            1083397 non-null  object
 8   latitude                           1067607 non-null  float64
 9   longitude                          1067607 non-null  float64
 10  claimed                            1081555 non-null  object
 11  awards                             263133 non-null   object
 12  popularity_detailed                988409 non-null   object
 13  popularity_generic                 985605 non-null   object
 14  top_tags                           972763 non-null   object
 15  price_level                        806192 non-null   object
 16  price_range                        304327 non-null   object
 17  meals                              635347 non-null   object
 18  cuisines                           914294 non-null   object
 19  special_diets                      340256 non-null   object
 20  features                           317407 non-null   object
 21  vegetarian_friendly                1083397 non-null  object
 22  vegan_options                      1083397 non-null  object
 23  gluten_free                        1083397 non-null  object
 24  original_open_hours                593832 non-null   object
 25  open_days_per_week                 593832 non-null   float64
 26  open_hours_per_week                593832 non-null   float64
 27  working_shifts_per_week            593832 non-null   float64
 28  avg_rating                         986761 non-null   float64
 29  total_reviews_count                1031162 non-null  float64
 30  default_language                   988204 non-null   object
 31  reviews_count_in_default_language  988204 non-null   float64
 32  excellent                          988204 non-null   float64
 33  very_good                          988204 non-null   float64
 34  average                            988204 non-null   float64
 35  poor                               988204 non-null   float64
 36  terrible                           988204 non-null   float64
 37  food                               599325 non-null   float64
 38  service                            604287 non-null   float64
 39  value                              602692 non-null   float64
 40  atmosphere                         261785 non-null   float64
 41  keywords                           99198 non-null    object
dtypes: float64(17), object(25)
memory usage: 347.2+ MB

None

-------------------------------------
Lister + count les pays de la colonne country

country
Italy               224763
Spain               157479
France              155288
England             144681
Germany             115333
Greece               33763
Portugal             32592
The Netherlands      29792
Poland               24698
Belgium              23711
Austria              20487
Sweden               18555
Czech Republic       14844
Scotland             14215
Ireland              11203
Denmark               9485
Wales                 9134
Croatia               8375
Romania               7842
Hungary               7431
Finland               7372
Bulgaria              4469
Slovakia              4251
Northern Ireland      3634
Name: count, dtype: int64

-------------------------------------
Lister + count les régions en France

region
Ile-de-France                 31271
Auvergne-Rhone-Alpes          20753
Provence-Alpes-Cote d'Azur    19925
Occitanie                     17775
Nouvelle-Aquitaine            15542
Grand Est                      9885
Hauts-de-France                7889
Brittany                       7568
Pays de la Loire               6527
Normandy                       6096
Bourgogne-Franche-Comte        5290
Centre-Val de Loire            4230
Corsica                        2535
Name: count, dtype: int64

# 2. Décrire les données  (région Ile-de-France)

### 2.1. Extraire les données de la région Ile-de-France

In [11]:
#créer un DataFrame filtré avec country = "France" ET region = "Ile-de-France"
df_trip = df_trip_eu[df_trip_eu["country"] == "France"]
print("Nombre de lignes et de colones")
print(df_trip.shape, "\n")
df_trip.head(3)

Nombre de lignes et de colones
(155288, 42)

,restaurant_link,restaurant_name,original_location,country,region,province,city,address,latitude,longitude,claimed,awards,popularity_detailed,popularity_generic,top_tags,price_level,price_range,meals,cuisines,special_diets,features,vegetarian_friendly,vegan_options,gluten_free,original_open_hours,open_days_per_week,open_hours_per_week,working_shifts_per_week,avg_rating,total_reviews_count,default_language,reviews_count_in_default_language,excellent,very_good,average,poor,terrible,food,service,value,atmosphere,keywords
0,g10001637-d10002227,Le 147,"[""Europe"", ""France"", ""Nouvelle-Aquitaine"", ""Ha...",France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,"10 Maison Neuve, 87510 Saint-Jouvent France",45.961674,1.169131,Claimed,None,#1 of 2 Restaurants in Saint-Jouvent,#1 of 2 places to eat in Saint-Jouvent,"Cheap Eats, French",€,None,"Lunch, Dinner",French,None,"Reservations, Seating, Wheelchair Accessible, ...",N,N,N,None,NaN,NaN,NaN,4.0,36.0,English,2.0,2.0,0.0,0.0,0.0,0.0,4.0,4.5,4.0,NaN,None
1,g10001637-d14975787,Le Saint Jouvent,"[""Europe"", ""France"", ""Nouvelle-Aquitaine"", ""Ha...",France,Nouvelle-Aquitaine,Haute-Vienne,Saint-Jouvent,"16 Place de l Eglise, 87510 Saint-Jouvent France",45.957040,1.205480,Unclaimed,None,#2 of 2 Restaurants in Saint-Jouvent,#2 of 2 places to eat in Saint-Jouvent,Cheap Eats,€,None,None,None,None,None,N,N,N,None,NaN,NaN,NaN,4.0,5.0,All languages,5.0,2.0,2.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,None
2,g10002858-d4586832,Au Bout du Pont,"[""Europe"", ""France"", ""Centre-Val de Loire"", ""B...",France,Centre-Val de Loire,Berry,Rivarennes,"2 rue des Dames, 36800 Rivarennes France",46.635895,1.386133,Claimed,None,#1 of 1 Restaurant in Rivarennes,#1 of 1 places to eat in Rivarennes,"Cheap Eats, French, European",€,None,"Dinner, Lunch, Drinks","French, European",None,"Reservations, Seating, Table Service, Wheelcha...",N,N,N,None,NaN,NaN,NaN,5.0,13.0,English,4.0,3.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,None

### 2.2. Résumer les valeurs uniques par colonnes

In [12]:
"""
Fonction générique : résumé des valeurs uniques par colonne. Pour chaque colonne :
- type (dtype)
- % de valeurs manquantes
- nombre de valeurs uniques
- aperçu des N premières valeurs unique
"""

def describe_unique_values(
    df: pd.DataFrame,
    max_unique_preview: int = 10,
    max_columns: int | None = None,
    include_object: bool = True,
    include_numeric: bool = True):
    """
    Affiche un résumé des valeurs uniques par colonne :
    - type de la colonne
    - pourcentage de valeurs manquantes
    - nombre de valeurs uniques
    - aperçu des premières valeurs uniques

    Paramètres
    ----------
    df : pd.DataFrame
        DataFrame à analyser
    max_unique_preview : int
        Nombre de valeurs uniques à afficher en aperçu
    max_columns : int | None
        Limiter le nombre de colonnes analysées (None = toutes)
    include_object : bool
        Inclure les colonnes de type object
    include_numeric : bool
        Inclure les colonnes numériques
    """

    cols = df.columns
    if max_columns:
        cols = cols[:max_columns]

    for col in cols:
        dtype = df[col].dtype

        if dtype == "object" and not include_object:
            continue
        if pd.api.types.is_numeric_dtype(dtype) and not include_numeric:
            continue

        total = len(df)
        missing = df[col].isna().sum()
        missing_pct = (missing / total) * 100
        unique_vals = df[col].dropna().unique()

        print("\n-------------------------------------")
        print(f"Colonne : {col}")
        print(f"Type : {dtype}")
        print(f"Valeurs manquantes : {missing_pct:.1f}%")
        print(f"Nombre de valeurs uniques : {len(unique_vals)}")
        print("-------------------------------------")

        display(unique_vals[:max_unique_preview])

#les colonnes object
describe_unique_values(df_trip)

-------------------------------------
Colonne : restaurant_link
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 155288
-------------------------------------

array(['g10001637-d10002227', 'g10001637-d14975787', 'g10002858-d4586832',
       'g10002986-d3510044', 'g10022428-d9767191', 'g10029260-d6605477',
       'g10029907-d17781655', 'g10029907-d8079764', 'g10036850-d8414223',
       'g10054961-d3387712'], dtype=object)

-------------------------------------
Colonne : restaurant_name
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 116439
-------------------------------------

array(['Le 147', 'Le Saint Jouvent', 'Au Bout du Pont',
       'Le Relais de Naiade', 'Relais Du MontSeigne',
       "L'Auberge Du Vieux Crozet", 'Cafe Restaurant NouLou', "L'entre 2",
       'Noste Courtiu', 'Chez Claudine'], dtype=object)

-------------------------------------
Colonne : original_location
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 15118
-------------------------------------

array(['["Europe", "France", "Nouvelle-Aquitaine", "Haute-Vienne", "Saint-Jouvent"]',
       '["Europe", "France", "Centre-Val de Loire", "Berry", "Indre", "Rivarennes"]',
       '["Europe", "France", "Nouvelle-Aquitaine", "Correze", "Lacelle"]',
       '["Europe", "France", "Occitanie", "Aveyron", "Saint-Laurent-de-Levezou"]',
       '["Europe", "France", "Auvergne-Rhone-Alpes", "Loire", "Roanne", "Le Crozet"]',
       '["Europe", "France", "Occitanie", "Aude", "Saint-Denis"]',
       '["Europe", "France", "Occitanie", "Ariege", "Orgibet"]',
       '["Europe", "France", "Grand Est", "Vosges", "They-sous-Montfort"]',
       '["Europe", "France", "Auvergne-Rhone-Alpes", "Ain", "Journans"]',
       '["Europe", "France", "Provence-Alpes-Cote d\'Azur", "Var", "Rocbaron"]'],
      dtype=object)

-------------------------------------
Colonne : country
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 1
-------------------------------------

array(['France'], dtype=object)

-------------------------------------
Colonne : region
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 13
-------------------------------------

array(['Nouvelle-Aquitaine', 'Centre-Val de Loire', 'Occitanie',
       'Auvergne-Rhone-Alpes', 'Grand Est', "Provence-Alpes-Cote d'Azur",
       'Normandy', 'Hauts-de-France', 'Pays de la Loire', 'Brittany'],
      dtype=object)

-------------------------------------
Colonne : province
Type : object
Valeurs manquantes : 11.8%
Nombre de valeurs uniques : 92
-------------------------------------

array(['Haute-Vienne', 'Berry', 'Correze', 'Aveyron', 'Loire', 'Aude',
       'Ariege', 'Vosges', 'Ain', 'Var'], dtype=object)

-------------------------------------
Colonne : city
Type : object
Valeurs manquantes : 0.1%
Nombre de valeurs uniques : 14673
-------------------------------------

array(['Saint-Jouvent', 'Rivarennes', 'Lacelle',
       'Saint-Laurent-de-Levezou', 'Le Crozet', 'Saint-Denis', 'Orgibet',
       'They-sous-Montfort', 'Journans', 'Rocbaron'], dtype=object)

-------------------------------------
Colonne : address
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 143733
-------------------------------------

array(['10 Maison Neuve, 87510 Saint-Jouvent France',
       '16 Place de l Eglise, 87510 Saint-Jouvent France',
       '2 rue des Dames, 36800 Rivarennes France',
       '9 avenue Porte de la Correze 19170, 19170 Lacelle France',
       'route du Montseigne, 12620 Saint-Laurent-de-Levezou France',
       '59 place du Puits ancienne adresse le Bourg renommée 59 place du Puits, 42310 Le Crozet, Roanne France',
       "Place de l'Église, 30500 Saint-Denis France",
       '4 route de Saissac, 11310 Saint-Denis France',
       'route des Pyrenees, 09800 Orgibet France',
       '136 rue de la Petite They, 88800 They-sous-Montfort France'],
      dtype=object)

-------------------------------------
Colonne : latitude
Type : float64
Valeurs manquantes : 1.2%
Nombre de valeurs uniques : 127915
-------------------------------------

array([45.961674, 45.95704 , 46.635895, 45.64261 , 44.20886 , 46.169823,
       44.233078, 43.360023, 42.934   , 48.231495])

-------------------------------------
Colonne : longitude
Type : float64
Valeurs manquantes : 1.2%
Nombre de valeurs uniques : 140326
-------------------------------------

array([1.169131, 1.20548 , 1.386133, 1.82446 , 2.96047 , 3.855819,
       4.251449, 2.219851, 0.936559, 5.973734])

-------------------------------------
Colonne : claimed
Type : object
Valeurs manquantes : 0.1%
Nombre de valeurs uniques : 2
-------------------------------------

array(['Claimed', 'Unclaimed'], dtype=object)

-------------------------------------
Colonne : awards
Type : object
Valeurs manquantes : 72.1%
Nombre de valeurs uniques : 532
-------------------------------------

array(["Travellers' Choice, Certificate of Excellence 2020",
       "Travellers' Choice, Certificate of Excellence 2020, Certificate of Excellence 2019, Certificate of Excellence 2018, Certificate of Excellence 2017",
       "Travellers' Choice, Certificate of Excellence 2020, Certificate of Excellence 2019, Certificate of Excellence 2018, Certificate of Excellence 2017, Certificate of Excellence 2016, Certificate of Excellence 2015",
       'Certificate of Excellence 2018, Certificate of Excellence 2017',
       "Travellers' Choice, Certificate of Excellence 2020, Certificate of Excellence 2019, Certificate of Excellence 2017, Certificate of Excellence 2016",
       'Certificate of Excellence 2016',
       "Travellers' Choice, Certificate of Excellence 2020, Certificate of Excellence 2018, Certificate of Excellence 2016, Certificate of Excellence 2015, Certificate of Excellence 2014",
       'Certificate of Excellence 2017, Certificate of Excellence 2016, Certificate of Excellence 2015',
       "Travellers' Choice, Certificate of Excellence 2020, Certificate of Excellence 2019, Certificate of Excellence 2018",
       "Travellers' Choice, Certificate of Excellence 2020, Certificate of Excellence 2019, Certificate of Excellence 2018, Certificate of Excellence 2017, Certificate of Excellence 2016, Certificate of Excellence 2015, Certificate of Excellence 2014, Certificate of Excellence 2013"],
      dtype=object)

-------------------------------------
Colonne : popularity_detailed
Type : object
Valeurs manquantes : 6.8%
Nombre de valeurs uniques : 143365
-------------------------------------

array(['#1 of 2 Restaurants in Saint-Jouvent',
       '#2 of 2 Restaurants in Saint-Jouvent',
       '#1 of 1 Restaurant in Rivarennes',
       '#1 of 1 Restaurant in Lacelle',
       '#1 of 1 Restaurant in Saint-Laurent-de-Levezou',
       '#1 of 1 Restaurant in Le Crozet',
       '#2 of 2 Restaurants in Saint-Denis',
       '#1 of 2 Restaurants in Saint-Denis',
       '#1 of 1 Restaurant in Orgibet',
       '#1 of 1 Restaurant in They-sous-Montfort'], dtype=object)

-------------------------------------
Colonne : popularity_generic
Type : object
Valeurs manquantes : 7.0%
Nombre de valeurs uniques : 142781
-------------------------------------

array(['#1 of 2 places to eat in Saint-Jouvent',
       '#2 of 2 places to eat in Saint-Jouvent',
       '#1 of 1 places to eat in Rivarennes',
       '#1 of 1 places to eat in Lacelle',
       '#1 of 1 places to eat in Saint-Laurent-de-Levezou',
       '#1 of 1 places to eat in Le Crozet',
       '#2 of 2 places to eat in Saint-Denis',
       '#1 of 2 places to eat in Saint-Denis',
       '#1 of 1 places to eat in Orgibet',
       '#1 of 1 places to eat in They-sous-Montfort'], dtype=object)

-------------------------------------
Colonne : top_tags
Type : object
Valeurs manquantes : 8.8%
Nombre de valeurs uniques : 7872
-------------------------------------

array(['Cheap Eats, French', 'Cheap Eats', 'Cheap Eats, French, European',
       'Mid-range, French', 'Mid-range, French, European',
       'Mid-range, French, European, Vegetarian Friendly',
       'Mid-range, French, Cafe, Deli',
       'Mid-range, French, European, Wine Bar',
       'Cheap Eats, French, Fast food', 'Chinese, Japanese'], dtype=object)

-------------------------------------
Colonne : price_level
Type : object
Valeurs manquantes : 19.2%
Nombre de valeurs uniques : 3
-------------------------------------

array(['€', '€€-€€€', '€€€€'], dtype=object)

-------------------------------------
Colonne : price_range
Type : object
Valeurs manquantes : 66.3%
Nombre de valeurs uniques : 3086
-------------------------------------

array(['€14-€29', '€8-€17', '€10-€35', '€12-€26', '€12-€30', '€10-€50',
       '€10-€30', '€7-€14', '€11-€23', '€26-€106'], dtype=object)

-------------------------------------
Colonne : meals
Type : object
Valeurs manquantes : 34.1%
Nombre de valeurs uniques : 404
-------------------------------------

array(['Lunch, Dinner', 'Dinner, Lunch, Drinks', 'Lunch, Dinner, Drinks',
       'After-hours, Drinks, Lunch, Dinner, Brunch', 'Dinner',
       'Lunch, Dinner, After-hours', 'Breakfast, Lunch, Dinner, Drinks',
       'Lunch', 'Lunch, Drinks, Dinner',
       'Lunch, Dinner, After-hours, Drinks'], dtype=object)

-------------------------------------
Colonne : cuisines
Type : object
Valeurs manquantes : 14.4%
Nombre de valeurs uniques : 12121
-------------------------------------

array(['French', 'French, European',
       'French, Cafe, Deli, Contemporary, Gastropub',
       'French, European, Wine Bar', 'French, Fast food',
       'Chinese, Japanese', 'French, American, German',
       'French, International', 'Pizza', 'Italian, French, Pizza'],
      dtype=object)

-------------------------------------
Colonne : special_diets
Type : object
Valeurs manquantes : 82.6%
Nombre de valeurs uniques : 31
-------------------------------------

array(['Vegetarian Friendly', 'Vegetarian Friendly, Vegan Options',
       'Gluten Free Options', 'Vegetarian Friendly, Halal',
       'Vegetarian Friendly, Vegan Options, Gluten Free Options', 'Halal',
       'Gluten Free Options, Vegetarian Friendly, Vegan Options',
       'Vegetarian Friendly, Gluten Free Options', 'Vegan Options',
       'Vegan Options, Vegetarian Friendly, Gluten Free Options'],
      dtype=object)

-------------------------------------
Colonne : features
Type : object
Valeurs manquantes : 60.5%
Nombre de valeurs uniques : 9514
-------------------------------------

array(['Reservations, Seating, Wheelchair Accessible, Serves Alcohol, Accepts Credit Cards, Table Service',
       'Reservations, Seating, Table Service, Wheelchair Accessible',
       'Reservations, Seating, Serves Alcohol, Table Service, Wheelchair Accessible',
       'Reservations, Seating, Wheelchair Accessible, Table Service',
       'Reservations, Seating, Table Service, Serves Alcohol',
       'Takeout, Wheelchair Accessible',
       'Takeout, Reservations, Wheelchair Accessible, Table Service',
       'Takeout, Reservations, Seating, Wheelchair Accessible, Serves Alcohol, Table Service, Outdoor Seating',
       'Takeout, Reservations, Outdoor Seating, Seating, Serves Alcohol, Table Service, Wheelchair Accessible',
       'Delivery, Takeout, Reservations, Seating, Wheelchair Accessible, Table Service, Serves Alcohol'],
      dtype=object)

-------------------------------------
Colonne : vegetarian_friendly
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['N', 'Y'], dtype=object)

-------------------------------------
Colonne : vegan_options
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['N', 'Y'], dtype=object)

-------------------------------------
Colonne : gluten_free
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['N', 'Y'], dtype=object)

-------------------------------------
Colonne : original_open_hours
Type : object
Valeurs manquantes : 45.0%
Nombre de valeurs uniques : 45088
-------------------------------------

array(['{"Mon": ["09:00-14:30"], "Tue": ["09:00-14:30", "19:00-21:30"], "Wed": ["09:00-14:30", "19:00-21:30"], "Thu": ["09:00-14:30", "19:00-21:30"], "Fri": ["09:00-14:30", "19:00-22:00"], "Sat": ["09:00-14:30", "19:00-22:00"], "Sun": ["09:00-16:00"]}',
       '{"Mon": [], "Tue": [], "Wed": ["12:00-14:30", "18:30-22:00"], "Thu": ["12:00-14:30", "18:30-22:00"], "Fri": ["12:00-14:30", "18:30-22:00"], "Sat": ["12:00-14:30", "18:30-22:00"], "Sun": ["12:00-14:30", "18:30-22:00"]}',
       '{"Mon": [], "Tue": ["10:00-14:00"], "Wed": ["10:00-14:00"], "Thu": ["10:00-14:00"], "Fri": ["10:00-14:00"], "Sat": ["10:00-14:00"], "Sun": ["10:00-14:00"]}',
       '{"Mon": [], "Tue": [], "Wed": ["12:00-14:00"], "Thu": ["12:00-14:00"], "Fri": ["12:00-14:00", "19:00-21:00"], "Sat": ["19:00-21:00"], "Sun": ["12:00-14:00", "19:00-21:00"]}',
       '{"Mon": [], "Tue": ["09:00-16:00"], "Wed": ["09:00-16:00"], "Thu": ["09:00-21:00"], "Fri": ["09:00-21:00"], "Sat": ["16:45-23:45"], "Sun": ["09:00-17:00"]}',
       '{"Mon": [], "Tue": ["11:00-13:30", "18:00-21:30"], "Wed": ["11:00-13:30", "18:00-21:30"], "Thu": ["11:00-13:30", "18:00-21:30"], "Fri": ["11:00-13:30", "18:00-21:30"], "Sat": ["11:00-13:30", "18:00-21:30"], "Sun": ["18:00-21:30"]}',
       '{"Mon": [], "Tue": ["11:30-14:30"], "Wed": ["11:30-14:30"], "Thu": ["11:30-14:30"], "Fri": ["11:30-13:30", "19:00-21:30"], "Sat": ["11:30-13:30", "19:00-21:30"], "Sun": ["11:30-14:00"]}',
       '{"Mon": ["07:00-20:00"], "Tue": ["07:00-20:00"], "Wed": ["07:00-20:00"], "Thu": ["07:00-20:00"], "Fri": ["07:00-23:00"], "Sat": ["07:00-23:00"], "Sun": ["07:00-17:00"]}',
       '{"Mon": ["11:45-14:15"], "Tue": ["11:45-14:15"], "Wed": ["11:45-14:15"], "Thu": ["11:45-14:15"], "Fri": ["11:45-14:15", "19:00-21:30"], "Sat": ["11:45-14:30", "19:00-21:30"], "Sun": []}',
       '{"Mon": ["11:30-14:00", "17:00-22:00"], "Tue": ["11:30-14:00", "17:00-22:00"], "Wed": ["11:30-14:00", "17:00-22:00"], "Thu": ["11:30-14:00", "17:00-22:00"], "Fri": ["11:30-14:00", "17:00-22:00"], "Sat": ["11:30-14:00", "17:00-22:00"], "Sun": ["11:30-14:00", "17:00-22:00"]}'],
      dtype=object)

-------------------------------------
Colonne : open_days_per_week
Type : float64
Valeurs manquantes : 45.0%
Nombre de valeurs uniques : 7
-------------------------------------

array([7., 5., 6., 1., 4., 2., 3.])

-------------------------------------
Colonne : open_hours_per_week
Type : float64
Valeurs manquantes : 45.0%
Nombre de valeurs uniques : 991
-------------------------------------

array([53.5 , 30.  , 24.  , 14.  , 53.  , 33.5 , 20.5 , 94.  , 20.25,
       52.5 ])

-------------------------------------
Colonne : working_shifts_per_week
Type : float64
Valeurs manquantes : 45.0%
Nombre de valeurs uniques : 15
-------------------------------------

array([12., 10.,  6.,  7., 11.,  8., 14., 13.,  9.,  2.])

-------------------------------------
Colonne : avg_rating
Type : float64
Valeurs manquantes : 7.0%
Nombre de valeurs uniques : 9
-------------------------------------

array([4. , 5. , 4.5, 3.5, 3. , 2. , 1. , 2.5, 1.5])

-------------------------------------
Colonne : total_reviews_count
Type : float64
Valeurs manquantes : 4.2%
Nombre de valeurs uniques : 1670
-------------------------------------

array([ 36.,   5.,  13.,  34.,  11.,  64.,  24., 133.,  39., 244.])

-------------------------------------
Colonne : default_language
Type : object
Valeurs manquantes : 6.9%
Nombre de valeurs uniques : 2
-------------------------------------

array(['English', 'All languages'], dtype=object)

-------------------------------------
Colonne : reviews_count_in_default_language
Type : float64
Valeurs manquantes : 6.9%
Nombre de valeurs uniques : 666
-------------------------------------

array([ 2.,  5.,  4.,  1., 11., 64., 13., 36., 37., 25.])

-------------------------------------
Colonne : excellent
Type : float64
Valeurs manquantes : 6.9%
Nombre de valeurs uniques : 444
-------------------------------------

array([ 2.,  3.,  1.,  4., 44.,  9., 18., 19., 36., 48.])

-------------------------------------
Colonne : very_good
Type : float64
Valeurs manquantes : 6.9%
Nombre de valeurs uniques : 296
-------------------------------------

array([ 0.,  2.,  1.,  7., 15.,  3., 12., 11.,  4., 28.])

-------------------------------------
Colonne : average
Type : float64
Valeurs manquantes : 6.9%
Nombre de valeurs uniques : 160
-------------------------------------

array([ 0.,  1.,  2.,  3.,  5., 10.,  6., 18., 11.,  7.])

-------------------------------------
Colonne : poor
Type : float64
Valeurs manquantes : 6.9%
Nombre de valeurs uniques : 106
-------------------------------------

array([ 0.,  2.,  1.,  4.,  3., 10.,  6.,  9., 12.,  5.])

-------------------------------------
Colonne : terrible
Type : float64
Valeurs manquantes : 6.9%
Nombre de valeurs uniques : 135
-------------------------------------

array([ 0.,  1.,  2.,  3.,  4.,  5., 12.,  6., 17.,  8.])

-------------------------------------
Colonne : food
Type : float64
Valeurs manquantes : 36.4%
Nombre de valeurs uniques : 9
-------------------------------------

array([4. , 4.5, 5. , 3.5, 3. , 2.5, 2. , 1.5, 1. ])

-------------------------------------
Colonne : service
Type : float64
Valeurs manquantes : 36.0%
Nombre de valeurs uniques : 9
-------------------------------------

array([4.5, 3.5, 4. , 5. , 3. , 2.5, 2. , 1.5, 1. ])

-------------------------------------
Colonne : value
Type : float64
Valeurs manquantes : 36.1%
Nombre de valeurs uniques : 9
-------------------------------------

array([4. , 4.5, 3.5, 5. , 3. , 2. , 2.5, 1.5, 1. ])

-------------------------------------
Colonne : atmosphere
Type : float64
Valeurs manquantes : 72.7%
Nombre de valeurs uniques : 9
-------------------------------------

array([4.5, 4. , 3.5, 5. , 3. , 2.5, 2. , 1. , 1.5])

-------------------------------------
Colonne : keywords
Type : object
Valeurs manquantes : 97.4%
Nombre de valeurs uniques : 3976
-------------------------------------

array(['pizza, tartiflette, fondue, service was excellent, chef',
       'tuna, fish, tapas, vineyard, region',
       'visited cafe, food was fantastic, both occasions, mascarpone, courses',
       'pates, apple tart, main course, wine list, set menu',
       'lunch, large trees, fantastic value, courses, euros',
       'chicken curry, mont saint michel, kevin, beer, accueil',
       'cheese board, boeuf, new owners, town square, wine list',
       'st jean, between courses, a la carte menu, superb service, reasonable choice',
       'st jean, excellent food, look no further, pascal, france',
       'pâté, roasted chicken, michelin restaurant, en croute, different ways'],
      dtype=object)

# 3. Les colonnes à prendre ou à laisser

### Les colonnes à garder abslument  :

**Dtype float**
- Itinéraire carte : latitude (0,5% missing), longitude (0,5% missing)

- Qualité globale : avg_rating (9,70% missing)

- Crédibilité: total_reviews_count (6,59% missing)


**Dtype object** :
- Filtres localisations géographiques : country (0% missing), region (0% missing), city (0,01% missing), address (0% missing)
  
- Identité : restaurant_name (0% missing), restaurant_link (0% missing)

- Statut + informations générales : claimed (0.11% missing), price_level (23.57% missing), price_range (66.99% missing), meals (38.54% missing), top_tags (12.81% missing), original_open_hours (42,49% missing)

- Labels alimentaires simples : vegetarian_friendly (0% missing), vegan_options (0% missing), gluten_free (0% missing)


### Les colonnes à transformer  :

- A transformer en score binaire (0/1) : awards (76.92% missing) 

- A transformer en proportions (%) : excellent (9.64% missing), very_good (9.64% missing), average (9.64%missing)

- A transformer en score moyen partiel : food (41.14% missing), service (40.87% missing), value (40.99% missing)

- A transformer en score d’accessibilité/Disponibilité/Flexibilité: open_days_per_week (42.49% missing)+ working_shifts_per_week (42.49% missing)

- A extraire l'option Halal de la colonne special_diets (79.30% missing) et les transformer en booléan

- A transformer en booléan : "vegetarian_friendly", "vegan_options", "gluten_free"


### Les colonnes à ignorer :
- Beaucoup de valeurs manquantes Dtype Float : atmosphere (74 % missing), open_hours_per_week (42,49% missing)

- Beaucoup de valeurs manquantes Dtype Object : keywords (96%), province (58% missing)

- Bruit: cuisines (18.92% missing), popularity_detailed (9.57% missing), popularity_generic (9.75% missing), original_location (0% missing), reviews_count_in_default_language (9.64% missing), poor (9.64% missing), terrible (9.64% missing), features (64.24% missing), default_language (9.64% missing)

# 4. Nettoyer + compléter + transformer les valeurs

### 4.1. Nettoyer

In [13]:
df_trip_clean = df_trip.copy()

#Supprimer toutes les lignes où latitude OU longitude est manquante (NaN)
df_trip_clean = df_trip_clean.dropna(subset=["latitude", "longitude"]).copy()

### 4.2. Compléter

In [14]:
#Créer une variable indicatrice pour avg_rating dont valeurs manquantes et la compléter avec une valeur neutre pondérée (median) dans une colonne à part pour l'étape score
df_trip_clean["avg_rating_missing"] = (df_trip_clean["avg_rating"].isna()).astype(int)
median_rating = df_trip_clean["avg_rating"].median()
df_trip_clean["avg_rating_filled"] = (df_trip_clean["avg_rating"].fillna(median_rating))

#Créer une variable indicatrice pour total_reviews_count dont valeurs manquantes et la compléter = 0
df_trip_clean["total_reviews_count_missing"] = (df_trip_clean["total_reviews_count"].isna()).astype(int)
df_trip_clean["total_reviews_count_filled"] = df_trip_clean["total_reviews_count"].fillna(0)

#Hypothèse raisonnable : un restaurant non revendiqué n’a probablement pas fait la démarche
df_trip_clean["claimed"] = df_trip_clean["claimed"].fillna("Unclaimed")

### 4.3. Transformer

#### 4.3.1 Colonne "awards" --> score binaire (0/1)

In [15]:
#transformer en score binaire (0/1) : awards (76.92% missing)
df_trip_clean["awards_binary"] = (df_trip_clean["awards"].notna()).astype(int)
df_trip_clean[["awards", "awards_binary"]].head(5)

  awards  awards_binary
0   None              0
1   None              0
2   None              0
3   None              0
4   None              0

#### 4.3.2 Colonnes "excellent", "very_good", "average" --> proportions (%)

In [16]:
#transformer en proportions (%) : excellent (9.64% missing), very_good (9.64% missing), average (9.64%missing)

#compléter les valeurs manquantes des colonnes "excellent", "very_good", "average" = 0
df_trip_clean[["excellent", "very_good", "average"]] = df_trip_clean[["excellent", "very_good", "average"]].fillna(0)

#les transformer en proportions (%) en basant sur la colonne "total_reviews_count"
df_trip_clean["excellent_pct"] = ((df_trip_clean["excellent"] / df_trip_clean["total_reviews_count"])*100).round(2)
df_trip_clean["very_good_pct"] = ((df_trip_clean["very_good"] / df_trip_clean["total_reviews_count"])*100).round(2)
df_trip_clean["average_pct"] = ((df_trip_clean["average"] / df_trip_clean["total_reviews_count"])*100).round(2)

#vérifier
df_trip_clean[["total_reviews_count","excellent","excellent_pct", "very_good", "very_good_pct", "average","average_pct"]].head(5)

,total_reviews_count,excellent,excellent_pct,very_good,very_good_pct,average,average_pct
0,36.0,2.0,5.56,0.0,0.00,0.0,0.0
1,5.0,2.0,40.00,2.0,40.00,1.0,20.0
2,13.0,3.0,23.08,1.0,7.69,0.0,0.0
3,34.0,1.0,2.94,0.0,0.00,0.0,0.0
4,11.0,4.0,36.36,7.0,63.64,0.0,0.0

#### 4.3.3 Colonnes "food", "service", "value" --> score moyen partiel

In [17]:
#transformer en score moyen partiel : food (41.14% missing), service (40.87% missing), value (40.99% missing)

#Créer le score moyen partiel en ignorant automatiquement les NaN + caculant la moyenne sur 1, 2 ou 3 colonnes + retournant NaN seulement si les 3 sont manquantes
df_trip_clean["partial_quality_score"] = ((df_trip_clean[["food", "service", "value"]].mean(axis=1, skipna=True))).round(2)

#Ajouter un indicateur de fiabilité (3=très fiable grace aux valeurs présentes sur les 3 colonnes, 2=fiable, 1=faible, 0=aucune info)
df_trip_clean["partial_quality_count"] = (df_trip_clean[["food", "service", "value"]].notna().sum(axis=1))

#Flager score partiel incomplet (inférieur à 3)
df_trip_clean["partial_quality_missing"] = (df_trip_clean["partial_quality_count"] < 3).astype(int)

#Score pondéré par la fiabilité
df_trip_clean["partial_quality_score_weighted"] = (df_trip_clean["partial_quality_score"] * (df_trip_clean["partial_quality_count"] / 3)).round(2)

#vérifier
df_trip_clean[["food", "service", "value", "partial_quality_score", "partial_quality_count", "partial_quality_score_weighted"]].head(5)

,food,service,value,partial_quality_score,partial_quality_count,partial_quality_score_weighted
0,4.0,4.5,4.0,4.17,3,4.17
1,NaN,NaN,NaN,NaN,0,NaN
2,NaN,NaN,NaN,NaN,0,NaN
3,4.5,4.5,4.5,4.50,3,4.50
4,4.5,4.5,4.5,4.50,3,4.50

#### 4.3.4 Colonnes "open_days_per_week", "working_shifts_per_week" --> score d’accessibilité

In [18]:
#transformer en score d’accessibilité/Disponibilité/Flexibilité: open_days_per_week (42.49% missing)+ working_shifts_per_week (42.49% missing)

#Créer un indicateurs sur les valeurs manquantes
df_trip_clean["open_days_missing"] = (df_trip_clean["open_days_per_week"].isna().astype(int))
df_trip_clean["working_shifts_missing"] = (df_trip_clean["working_shifts_per_week"].isna().astype(int))

#Normaliser les deux variables (0 → 1)
df_trip_clean["open_days_norm"] = ((df_trip_clean["open_days_per_week"] / 7)).round(2)
df_trip_clean["working_shifts_norm"] = ((df_trip_clean["working_shifts_per_week"] / 14)).round(2)

#Score d’accessibilité partiel
df_trip_clean["accessibility_score"] = ((df_trip_clean[["open_days_norm", "working_shifts_norm"]].mean(axis=1, skipna=True))).round(2)

#Fiabilité du score : 2=très fiable, 1=partiel, 0=aucune info
df_trip_clean["accessibility_count"] = (df_trip_clean[["open_days_norm", "working_shifts_norm"]].notna().sum(axis=1))

#Flag “accessibilité incomplète”
df_trip_clean["accessibility_missing"] = (df_trip_clean["accessibility_count"] < 2).astype(int)

#Mise à l’échelle finale
df_trip_clean["accessibility_score_5"] = (df_trip_clean["accessibility_score"] * 5).round(2)

#vérifier
df_trip_clean[["open_days_per_week", "working_shifts_per_week", "open_days_norm", "working_shifts_norm",
                 "accessibility_score", "accessibility_count", "accessibility_score_5"]].head(5)

,open_days_per_week,working_shifts_per_week,open_days_norm,working_shifts_norm,accessibility_score,accessibility_count,accessibility_score_5
0,NaN,NaN,NaN,NaN,NaN,0,NaN
1,NaN,NaN,NaN,NaN,NaN,0,NaN
2,NaN,NaN,NaN,NaN,NaN,0,NaN
3,NaN,NaN,NaN,NaN,NaN,0,NaN
4,NaN,NaN,NaN,NaN,NaN,0,NaN

#### 4.3.5 Extraire l'option Halal & kosher de la colonne special_diets (79.30% missing) --> booléenne

In [19]:
# Création de la colonne booléenne halal
df_trip_clean['is_halal'] = df_trip_clean['special_diets'].str.contains('Halal', case=False, na=False)
# Vérification
display(df_trip_clean['is_halal'].value_counts())

# Création de la colonne booléenne kosher
df_trip_clean['is_kosher'] = df_trip_clean['special_diets'].str.contains('kosher', case=False, na=False)
# Vérification
display(df_trip_clean['is_kosher'].value_counts())

is_halal
False    152754
True        605
Name: count, dtype: int64

is_kosher
False    153274
True         85
Name: count, dtype: int64

#### 4.3.6 Transformer en booléan : "vegetarian_friendly", "vegan_options", "gluten_free" --> créer une colonne "diet_level" pour UX streamlit

In [20]:
#Transformation directe Y → True, N → False
cols = ["vegetarian_friendly", "vegan_options", "gluten_free"]
df_trip_clean[cols] = (df_trip_clean[cols].replace({'Y': True, 'N': False}).astype(bool))

C:\Users\DELL\AppData\Local\Temp\ipykernel_11440\2746076239.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_trip_clean[cols] = (df_trip_clean[cols].replace({'Y': True, 'N': False}).astype(bool))

#### 4.3.7 Créer une colonne url en basant sur la colonne "restaurant_link"

In [21]:
#Créer une colonne url en basant sur la colonne "restaurant_link"
df_trip_clean["url"] = ("https://www.tripadvisor.fr/Restaurant_Review-" + df_trip_clean["restaurant_link"].astype(str) + ".html")
#vérifier
df_trip_clean[["restaurant_link", "url"]]

            restaurant_link                                                url
0       g10001637-d10002227  https://www.tripadvisor.fr/Restaurant_Review-g...
1       g10001637-d14975787  https://www.tripadvisor.fr/Restaurant_Review-g...
2        g10002858-d4586832  https://www.tripadvisor.fr/Restaurant_Review-g...
3        g10002986-d3510044  https://www.tripadvisor.fr/Restaurant_Review-g...
4        g10022428-d9767191  https://www.tripadvisor.fr/Restaurant_Review-g...
...                     ...                                                ...
155283    g9859641-d7744064  https://www.tripadvisor.fr/Restaurant_Review-g...
155284    g9862396-d7285125  https://www.tripadvisor.fr/Restaurant_Review-g...
155285    g9863068-d8560009  https://www.tripadvisor.fr/Restaurant_Review-g...
155286   g9980751-d16852973  https://www.tripadvisor.fr/Restaurant_Review-g...
155287    g9984709-d5854089  https://www.tripadvisor.fr/Restaurant_Review-g...

[153359 rows x 2 columns]

#### 4.3.8 catégoriser la colonne "price_level" en petit (1), moyen (2) et confort (3) budget

In [22]:
#Créer une catégorie explicite Unknown pour les price_level dont valeurs manquantes
df_trip_clean["price_level"] = df_trip_clean["price_level"].fillna("Unknown")

#mapper les valeurs
price_mapping = {"€": 1, "€€-€€€": 2, "€€€€": 3}
df_trip_clean["price_category"] = (df_trip_clean["price_level"].map(price_mapping).fillna(1))

#vérifier
df_trip_clean["price_category"].value_counts()

price_category
2.0    85861
1.0    61427
3.0     6071
Name: count, dtype: int64

#### 4.3.9 transformer la colonne "cuisines" en tags normalisés + colonnes booléennes.

In [23]:
## DEF : Normaliser + tokenizer meals
def parse_cuisines(x):
    if pd.isna(x) or str(x).strip() == "" or str(x).strip().lower() == "none":
        return []
    items = [t.strip() for t in str(x).split(",")]
    items = [t for t in items if t]
    # Normalisation simple (optionnel)
    # ex: uniformiser "Fast food" vs "Fast food " etc.
    return items

df_trip_clean["cuisines_list"] = df_trip_clean["cuisines"].apply(parse_cuisines)

display(df_trip_clean["cuisines_list"])

# count les mots
cuisine_word_counts = (df_trip_clean["cuisines_list"].explode().value_counts().reset_index())
cuisine_word_counts.columns = ["cuisine", "count"]
#pd.set_option("display.max_rows", None)
display(cuisine_word_counts)

0                              [French]
1                                    []
2                    [French, European]
3                              [French]
4                              [French]
                      ...
155283    [French, American, Fast food]
155284                         [French]
155285                         [French]
155286                       [European]
155287                         [French]
Name: cuisines_list, Length: 153359, dtype: object

           cuisine  count
0           French  83832
1         European  31623
2          Italian  16040
3            Pizza  12430
4    Mediterranean  10844
..             ...    ...
150          Kappo      1
151    Costa Rican      1
152       Nigerian      1
153        Lombard      1
154          Balti      1

[155 rows x 2 columns]

In [24]:
CUISINE_BY_CONTINENT = {"Européen": {"European", "French", "Italian", "Southern-Italian", "Central-Italian", "Northern-Italian", "Neapolitan", "Sicilian", "Sardinian", "Tuscan", "Campania", "Lazio",
                                     "Romana", "Apulian", "Calabrian", "Romagna", "Spanish", "Catalan", "Greek", "Portuguese", "Belgian", "British", "Irish", "Scottish", "Welsh",
                                     "German", "Swiss", "Austrian", "Dutch", "Scandinavian", "Swedish", "Norwegian", "Danish", "Polish", "Hungarian", "Romanian", "Croatian",
                                     "Albanian", "Ukrainian", "Russian", "Central European", "Eastern European"},
                        "Asiatique": {"Asian", "Japanese", "Japanese Fusion", "Sushi", "Chinese", "Beijing cuisine", "Fujian", "Xinjiang", "Yunnan", "Korean", "Vietnamese", "Thai",
                                  "Indian", "Pakistani", "Bangladeshi", "Sri Lankan", "Nepalese", "Tibetan", "Indonesian", "Malaysian", "Singaporean", "Taiwanese", "Philippine", "Mongolian",
                                  "Central Asian", "Uzbek", "Afghani"},
                        "Moyen-Orient": {"Middle Eastern", "Lebanese", "Israeli", "Persian", "Arabic", "Armenian", "Assyrian"},
                        "Africain": {"African", "Moroccan", "Tunisian", "Algerian", "Egyptian", "Ethiopian", "Nigerian"},
                        "Américain": {"American", "Mexican", "South American", "Brazilian", "Argentinian", "Peruvian", "Colombian", "Chilean", "Venezuelan", "Canadian", "Native American", "Southwestern"},
                        "Caraïbes": {"Caribbean", "Jamaican", "Cuban", "Puerto Rican", "Bahamian"},
                        "International": {"International", "Fusion", "Contemporary", "Medicinal foods", "Caucasian"},
                        "Autres": {"Medicinal foods", "Caucasian"}}

CUISINE_TYPE_MAP = {
    "Fast food": "Fast-Food",
    "Street Food": "Street-Food",
    "Pizza": "Pizza",
    "Diner": "Diner",

    "Bar": "Bar",
    "Pub": "Bar",
    "Wine Bar": "Bar",
    "Brew Pub": "Bar",
    "Dining bars": "Bar",
    "Beer restaurants": "Bar",

    "Cafe": "Café",
    "Deli": "Deli",

    "Healthy": "Healthy",
    "Soups": "Healthy",
    "Medicinal foods": "Healthy",

    "Grill": "Grill",
    "Barbecue": "Grill",
    "Steakhouse": "Steakhouse",

    "Seafood": "Seafood",
    "Sushi": "Sushi",
    "Japanese sweets parlour": "Sweets",
    "Fruit parlours": "Sweets",

    "Gastropub": "Gastropub",
    "Contemporary": "Gastronomic",
    "Fusion": "Fusion",}

# 1) mapping inverse cuisine -> continent
CUISINE_CONTINENT_MAP = {
    cuisine: continent
    for continent, cuisines in CUISINE_BY_CONTINENT.items()
    for cuisine in cuisines}

# 2) fonctions correctes
def get_cuisine_continent(cuisines_list):
    if not isinstance(cuisines_list, list):
        return "Autres"
    for c in cuisines_list:
        continent = CUISINE_CONTINENT_MAP.get(c)
        if continent:
            return continent
    return "Autres"

def get_cuisine_type(cuisines_list):
    if not isinstance(cuisines_list, list):
        return "Other"
    for c in cuisines_list:
        cuisine_type = CUISINE_TYPE_MAP.get(c)
        if cuisine_type:
            return cuisine_type
    return "Autres"

# 3) apply (PAS map)
df_trip_clean["cuisine_continent"] = df_trip_clean["cuisines_list"].apply(get_cuisine_continent)
df_trip_clean["cuisine_type"] = df_trip_clean["cuisines_list"].apply(get_cuisine_type)

df_trip_clean[["cuisines_list", "cuisine_continent", "cuisine_type"]]

                        cuisines_list cuisine_continent cuisine_type
0                            [French]          Européen       Autres
1                                  []            Autres       Autres
2                  [French, European]          Européen       Autres
3                            [French]          Européen       Autres
4                            [French]          Européen       Autres
...                               ...               ...          ...
155283  [French, American, Fast food]          Européen    Fast-Food
155284                       [French]          Européen       Autres
155285                       [French]          Européen       Autres
155286                     [European]          Européen       Autres
155287                       [French]          Européen       Autres

[153359 rows x 3 columns]

#### 4.3.10 Calculer un score final en basant sur 4 catégories scores --> formule : RecoScore=100×(0.40⋅Q+0.25⋅E+0.20⋅R+0.15⋅A)

Q = (40 %) qualité globale (rating) = "avg_rating_filled",

E = (25 %) excellence (avis “Excellent”) = "excellent_pct",

R = (20 %) fiabilité (volume d’avis) = "total_reviews_count_filled",

A = (15 %) accessibilité (horaires) = "accessibility_score_5"

Lecture du score : 85 – 100 = Exceptionnel ; 70 – 85 = Très recommandé ; 55 – 70 = Correct ; < 55	= Peu recommandé

In [25]:
#1) Normalisations
# Rating global
df_trip_clean["Q_rating"] = df_trip_clean["avg_rating_filled"] / 5

# Qualité fine (food / service / value)
df_trip_clean["Q_partial"] = (df_trip_clean["partial_quality_score_weighted"].fillna(df_trip_clean["partial_quality_score_weighted"].median()) / 5)

# Excellence
df_trip_clean["E"] = df_trip_clean["excellent_pct"].fillna(0) / 100

# Fiabilité
df_trip_clean["R"] = np.log1p(df_trip_clean["total_reviews_count_filled"]) / np.log1p(df_trip_clean["total_reviews_count_filled"].max())

# Accessibilité
df_trip_clean["A"] = (df_trip_clean["accessibility_score_5"].fillna(df_trip_clean["accessibility_score_5"].median()) / 5)

# 2) Qualité globale (Q combinée) : combiner rating global (70%) + qualité fine (30%) :
df_trip_clean["Q"] = 0.7 * df_trip_clean["Q_rating"] + 0.3 * df_trip_clean["Q_partial"]

# 3) Score final de recommandation streamlit
df_trip_clean["reco_score"] = (100 * (0.40 * df_trip_clean["Q"] + 0.25 * df_trip_clean["E"] + 0.20 * df_trip_clean["R"] + 0.15 * df_trip_clean["A"]) + (df_trip_clean["awards_binary"] * 3)).round(2)

df_trip_clean[["Q_rating", "Q_partial", "Q", "E", "R", "reco_score"]]

        Q_rating  Q_partial       Q       E         R  reco_score
0            0.8      0.834  0.8102  0.0556  0.375031       52.55
1            0.8      0.834  0.8102  0.4000  0.186093       57.38
2            1.0      0.834  0.9502  0.2308  0.274093       60.51
3            0.8      0.900  0.8300  0.0294  0.369259       52.57
4            0.9      0.900  0.9000  0.3636  0.258083       61.50
...          ...        ...     ...     ...       ...         ...
155283       0.8      0.834  0.8102  0.5000  0.202103       60.20
155284       0.8      0.800  0.8000  0.0000  0.202103       45.64
155285       0.8      0.734  0.7802  0.0204  0.406304       50.64
155286       0.8      0.834  0.8102  0.0000  0.000000       43.66
155287       0.7      0.734  0.7102  0.2273  0.325653       51.85

[153359 rows x 6 columns]

#### 4.3.11 Créer une colonne "postal_code" par extraire la colonne "adresse"

In [26]:
#extraire code postal de la colonne "adresse"
df_trip_clean["postal_code"] = (df_trip_clean["address"].astype(str).str.extract(r"\b(\d{5})\b", expand=False))
df_trip_clean[["address", "postal_code"]]

                                                  address postal_code
0             10 Maison Neuve, 87510 Saint-Jouvent France       87510
1        16 Place de l Eglise, 87510 Saint-Jouvent France       87510
2                2 rue des Dames, 36800 Rivarennes France       36800
3       9 avenue Porte de la Correze 19170, 19170 Lace...       19170
4       route du Montseigne, 12620 Saint-Laurent-de-Le...       12620
...                                                   ...         ...
155283  138 avenue des Martyrs Le bowling De Montlucon...       03410
155284      1 rue de la Sucrerie, 76400 Colleville France       76400
155285  14 rue de Marlenheim, 67117 Fessenheim-le-Bas ...       67117
155286  14 route de Flandres, 95500 Bonneuil-en-France...       95500
155287  Domaine de la forteresse, 77940 Thoury-Ferrott...       77940

[153359 rows x 2 columns]

# 5. DataFrame Final (normer les colonnes afin de mapper avec les autres datasets dans streamlit)

19 colonnes normées UX streamlit : source_id, source, type, raw_type, url, lat, lon, name, address, postal_code, city, region, country, snippet, rating, review_count, price_level, max_people, distance_km

In [27]:
# Garder uniquement les colonnes utiles
cols_keep = ["restaurant_link", "restaurant_name", "country", "region", "city", "address", "latitude", "longitude", "postal_code",
             "avg_rating_filled", "total_reviews_count_filled", "url", "price_category", "reco_score",
             "vegetarian_friendly", "vegan_options", "gluten_free", "is_halal", "is_kosher","cuisine_continent", "cuisine_type"]

df_trip_clean_norm = df_trip_clean[cols_keep].copy()

# Colonnes standard (type + distance_km placeholder)
df_trip_clean_norm["source"] = "tripadvisor_european_restaurants"
df_trip_clean_norm["type"] = "Restaurant"
df_trip_clean_norm["distance_km"] = np.nan
df_trip_clean_norm["max_people"] = np.nan

# Normaliser / renommer

rename_map={"restaurant_link": "source_id",
            "restaurant_name": "name",
            "latitude": "lat",
            "longitude": "lon",
            "cuisines_list": " snippet",
            "price_category": "price_level",
            "avg_rating_filled": "rating",
            "total_reviews_count_filled": "review_count"}
df_trip_clean_normux = df_trip_clean_norm.rename(columns = rename_map, errors="ignore")

# réordonner les colonnes UX
UX_COLUMNS = ["source_id", "source", "type", "url", "lat", "lon",
              "name", "address", "postal_code", "city", "region", "country",
              "snippet", "rating", "review_count", "price_level", "reco_score",
              "cuisine_continent", "cuisine_type", "vegetarian_friendly", "vegan_options",
              "gluten_free", "is_halal", "is_kosher", "max_people", "distance_km"]

for col in UX_COLUMNS:
    if col not in df_trip_clean_normux.columns:
        df_trip_clean_normux[col] = None
        
df_trip_clean_normux_ = df_trip_clean_normux[UX_COLUMNS]

#sauvegarder les changements
df_tripadvisor_France = df_trip_clean_normux_.copy()

# Export parquet final (un seul fichier)
df_tripadvisor_France.to_parquet("df_tripadvisor_France.parquet", index=False)

display(df_tripadvisor_France.head(2))
display(df_tripadvisor_France.info())

,source_id,source,type,url,lat,lon,name,address,postal_code,city,region,country,snippet,rating,review_count,price_level,reco_score,cuisine_continent,cuisine_type,vegetarian_friendly,vegan_options,gluten_free,is_halal,is_kosher,max_people,distance_km
0,g10001637-d10002227,tripadvisor_european_restaurants,Restaurant,https://www.tripadvisor.fr/Restaurant_Review-g...,45.961674,1.169131,Le 147,"10 Maison Neuve, 87510 Saint-Jouvent France",87510,Saint-Jouvent,Nouvelle-Aquitaine,France,None,4.0,36.0,1.0,52.55,Européen,Autres,False,False,False,False,False,NaN,NaN
1,g10001637-d14975787,tripadvisor_european_restaurants,Restaurant,https://www.tripadvisor.fr/Restaurant_Review-g...,45.957040,1.205480,Le Saint Jouvent,"16 Place de l Eglise, 87510 Saint-Jouvent France",87510,Saint-Jouvent,Nouvelle-Aquitaine,France,None,4.0,5.0,1.0,57.38,Autres,Autres,False,False,False,False,False,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
Index: 153359 entries, 0 to 155287
Data columns (total 26 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   source_id            153359 non-null  object
 1   source               153359 non-null  object
 2   type                 153359 non-null  object
 3   url                  153359 non-null  object
 4   lat                  153359 non-null  float64
 5   lon                  153359 non-null  float64
 6   name                 153359 non-null  object
 7   address              153359 non-null  object
 8   postal_code          150272 non-null  object
 9   city                 153251 non-null  object
 10  region               153357 non-null  object
 11  country              153359 non-null  object
 12  snippet              0 non-null       object
 13  rating               153359 non-null  float64
 14  review_count         153359 non-null  float64
 15  price_level          153359 non-null  float64
 16  reco_score           153359 non-null  float64
 17  cuisine_continent    153359 non-null  object
 18  cuisine_type         153359 non-null  object
 19  vegetarian_friendly  153359 non-null  bool
 20  vegan_options        153359 non-null  bool
 21  gluten_free          153359 non-null  bool
 22  is_halal             153359 non-null  bool
 23  is_kosher            153359 non-null  bool
 24  max_people           0 non-null       float64
 25  distance_km          0 non-null       float64
dtypes: bool(5), float64(8), object(13)
memory usage: 26.5+ MB

None