# Dataset — AirBnb Paris
(1,12 GB, 5 file, 108 columns, 703 downloads, Updated 7 years ago)

https://www.kaggle.com/datasets/juliatb/airbnb-paris?select=reviews.csv

In [1]:
import pandas as pd
import numpy as np
import pyarrow
import json

# 1. Charger les données

### 1.1. Dataset "listings.csv"

In [2]:
#lire CSV_PATH
CSV_PATH = "df_airBnb_paris.csv"
df_listings = pd.read_csv(CSV_PATH, sep=',', encoding='utf-8', low_memory = False)

#Afficher 2 lignes et TOUTES les colonnes
pd.set_option("display.max_columns", None)
display(df_listings.head(3))

print("\n-------------------------------------")
print("Nombre de lignes et de colones")
print(df_listings.shape)

print("\n-------------------------------------")
print("Display info sur les colonnes et datatype")
display(df_listings.info())

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,2577,https://www.airbnb.com/rooms/2577,20181207151406,2018-12-08,Loft for 4 by Canal Saint Martin,"100 m2 loft (1100 sq feet) with high ceiling, ...",The district has any service or shop you may d...,"100 m2 loft (1100 sq feet) with high ceiling, ...",none,NaN,NaN,"Metro lines : 4, 8, 3, 11, 9.",NaN,NaN,NaN,NaN,NaN,https://a0.muscache.com/im/pictures/09da057c-0...,NaN,2827,https://www.airbnb.com/users/show/2827,Karine,2008-09-09,"Casablanca, Grand Casablanca, Morocco","Arrivée à Casablanca il y a 4 ans, je suis amo...",within a day,75%,NaN,f,https://a0.muscache.com/im/pictures/17fe6c88-a...,https://a0.muscache.com/im/pictures/17fe6c88-a...,République,2.0,2.0,"['email', 'phone', 'reviews', 'jumio', 'govern...",t,t,"Paris, Île-de-France, France",République,Entrepôt,NaN,Paris,Île-de-France,75010,Paris,"Paris, France",FR,France,48.869933,2.362511,t,Loft,Entire home/apt,4,2.0,2.0,2.0,Real Bed,"{TV,Internet,Wifi,Kitchen,Heating,Washer,Dryer...",NaN,$125.00,NaN,NaN,$0.00,$40.00,1,$0.00,3,1125,4 weeks ago,t,12,13,13,39,2018-12-08,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN,{PARIS},t,f,strict_14_with_grace_period,f,f,1,NaN
1,3109,https://www.airbnb.com/rooms/3109,20181207151406,2018-12-08,zen and calm,Appartement très calme de 50M2 Belle lumière D...,I bedroom appartment in Paris 14,I bedroom appartment in Paris 14,none,NaN,NaN,"ligne 13 and RER B, Ligne 4",NaN,yes I can help you out,NaN,NaN,NaN,https://a0.muscache.com/im/pictures/baeae9e2-c...,NaN,3631,https://www.airbnb.com/users/show/3631,Anne,2008-10-14,"Paris, Île-de-France, France",NaN,within a day,100%,NaN,f,https://a0.muscache.com/im/users/3631/profile_...,https://a0.muscache.com/im/users/3631/profile_...,Alésia,1.0,1.0,"['email', 'phone', 'facebook', 'reviews']",t,f,"Paris, Île-de-France, France",Alésia,Observatoire,NaN,Paris,Île-de-France,75014,Paris,"Paris, France",FR,France,48.833494,2.318518,f,Apartment,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{Internet,Wifi,Kitchen,""Paid parking off premi...",NaN,$75.00,$490.00,NaN,$0.00,$50.00,1,$0.00,3,15,5 days ago,t,3,4,17,271,2018-12-08,7,2016-12-27,2018-07-27,100.0,10.0,10.0,10.0,10.0,10.0,10.0,t,NaN,{PARIS},f,f,flexible,f,f,1,0.29
2,5396,https://www.airbnb.com/rooms/5396,20181207151406,2018-12-08,Explore the heart of old Paris,"Cozy, well-appointed and graciously designed s...","Small, well appointed studio apartment at the ...","Cozy, well-appointed and graciously designed s...",none,"You are within walking distance to the Louvre,...",The staircase leading up to the apartment is n...,The flat is close to two or three major metro ...,"The flat includes its own modern bathroom, a w...",We expect guests to operate rather independent...,This is a small flat in a very old building th...,NaN,NaN,https://a0.muscache.com/im/pictures/52413/f9bf...,NaN,7903,https://www.airbnb.com/users/show/7903,Borzou,2009-02-14,"Istanbul, İstanbul, Turkey",We are both journalists based in the Middle Ea...,within an hour,100%,NaN,f,https://a0.muscache.com/im/users/7903/profile_...,https://a0.muscache.com/im/users/7903/profile_...,Saint-Paul - Ile Saint-Louis,1.0,1.0,"['email', 'phone', 'facebook', 'google', 'revi...",t,t,"Paris, Ile-de-France, France",Saint-Paul - Ile Saint-Louis,Hôtel-de-Ville,NaN,Paris,Ile-de-France,75004,Paris,"Paris, France",FR,France,48.851001,2.358690,t,Apartment,Entire home/apt,2,1.0,0.0,1.0,Pull-out Sofa,"{TV,""Cable TV"",Internet,Wifi,Kitchen,Heating,W...",NaN,$115.00,$600.00,"$2,000.00",$0.00,$36.00,1,$0.00,2,30,6 days ago,t,1,6,28,113,2018-12-08,148,2009-06-30,2018-11-21,94.0,9.0,9.0,10.0,10.0,10.0,10.0,t,NaN,{PARIS},t,f,strict_14_with_grace_period,f,f,1,1.29

-------------------------------------
Nombre de lignes et de colones
(59881, 96)

-------------------------------------
Display info sur les colonnes et datatype
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59881 entries, 0 to 59880
Data columns (total 96 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                59881 non-null  int64
 1   listing_url                       59881 non-null  object
 2   scrape_id                         59881 non-null  int64
 3   last_scraped                      59881 non-null  object
 4   name                              59807 non-null  object
 5   summary                           57524 non-null  object
 6   space                             40516 non-null  object
 7   description                       59384 non-null  object
 8   experiences_offered               59881 non-null  object
 9   neighborhood_overview             35647 non-null  object
 10  notes                             18605 non-null  object
 11  transit                           38160 non-null  object
 12  access                            28846 non-null  object
 13  interaction                       28357 non-null  object
 14  house_rules                       28475 non-null  object
 15  thumbnail_url                     0 non-null      float64
 16  medium_url                        0 non-null      float64
 17  picture_url                       59881 non-null  object
 18  xl_picture_url                    0 non-null      float64
 19  host_id                           59881 non-null  int64
 20  host_url                          59881 non-null  object
 21  host_name                         59873 non-null  object
 22  host_since                        59873 non-null  object
 23  host_location                     59690 non-null  object
 24  host_about                        30360 non-null  object
 25  host_response_time                30971 non-null  object
 26  host_response_rate                30971 non-null  object
 27  host_acceptance_rate              0 non-null      float64
 28  host_is_superhost                 59873 non-null  object
 29  host_thumbnail_url                59873 non-null  object
 30  host_picture_url                  59873 non-null  object
 31  host_neighbourhood                51279 non-null  object
 32  host_listings_count               59873 non-null  float64
 33  host_total_listings_count         59873 non-null  float64
 34  host_verifications                59873 non-null  object
 35  host_has_profile_pic              59873 non-null  object
 36  host_identity_verified            59873 non-null  object
 37  street                            59881 non-null  object
 38  neighbourhood                     57231 non-null  object
 39  neighbourhood_cleansed            59881 non-null  object
 40  neighbourhood_group_cleansed      0 non-null      float64
 41  city                              59860 non-null  object
 42  state                             59151 non-null  object
 43  zipcode                           59084 non-null  object
 44  market                            59749 non-null  object
 45  smart_location                    59881 non-null  object
 46  country_code                      59881 non-null  object
 47  country                           59881 non-null  object
 48  latitude                          59881 non-null  float64
 49  longitude                         59881 non-null  float64
 50  is_location_exact                 59881 non-null  object
 51  property_type                     59881 non-null  object
 52  room_type                         59881 non-null  object
 53  accommodates                      59881 non-null  int64
 54  bathrooms                         59805 non-null  float64
 55  bedrooms                          59813 non-null  float64
 56  beds                              59653 non-null  float64
 57  bed_type                          59881 non-null  object
 58  amenities                         59881 non-null  object
 59  square_feet                       1358 non-null   float64
 60  price                             59881 non-null  object
 61  weekly_price                      12142 non-null  object
 62  monthly_price                     7787 non-null   object
 63  security_deposit                  40825 non-null  object
 64  cleaning_fee                      43119 non-null  object
 65  guests_included                   59881 non-null  int64
 66  extra_people                      59881 non-null  object
 67  minimum_nights                    59881 non-null  int64
 68  maximum_nights                    59881 non-null  int64
 69  calendar_updated                  59881 non-null  object
 70  has_availability                  59881 non-null  object
 71  availability_30                   59881 non-null  int64
 72  availability_60                   59881 non-null  int64
 73  availability_90                   59881 non-null  int64
 74  availability_365                  59881 non-null  int64
 75  calendar_last_scraped             59881 non-null  object
 76  number_of_reviews                 59881 non-null  int64
 77  first_review                      47389 non-null  object
 78  last_review                       47389 non-null  object
 79  review_scores_rating              46289 non-null  float64
 80  review_scores_accuracy            46224 non-null  float64
 81  review_scores_cleanliness         46245 non-null  float64
 82  review_scores_checkin             46192 non-null  float64
 83  review_scores_communication       46230 non-null  float64
 84  review_scores_location            46193 non-null  float64
 85  review_scores_value               46192 non-null  float64
 86  requires_license                  59881 non-null  object
 87  license                           14557 non-null  object
 88  jurisdiction_names                59119 non-null  object
 89  instant_bookable                  59881 non-null  object
 90  is_business_travel_ready          59881 non-null  object
 91  cancellation_policy               59881 non-null  object
 92  require_guest_profile_picture     59881 non-null  object
 93  require_guest_phone_verification  59881 non-null  object
 94  calculated_host_listings_count    59881 non-null  int64
 95  reviews_per_month                 47389 non-null  float64
dtypes: float64(21), int64(13), object(62)
memory usage: 43.9+ MB

None

# 2. Décrire les colonnes essentielles du dataset "listings.csv"

In [3]:
"""
Fonction générique : résumé des valeurs uniques par colonne. Pour chaque colonne :
- type (dtype)
- % de valeurs manquantes
- nombre de valeurs uniques
- aperçu des N premières valeurs unique
"""

def describe_unique_values(
    df: pd.DataFrame,
    max_unique_preview: int = 10,
    max_columns: int | None = None,
    include_object: bool = True,
    include_numeric: bool = True):
    """
    Affiche un résumé des valeurs uniques par colonne :
    - type de la colonne
    - pourcentage de valeurs manquantes
    - nombre de valeurs uniques
    - aperçu des premières valeurs uniques

    Paramètres
    ----------
    df : pd.DataFrame
        DataFrame à analyser
    max_unique_preview : int
        Nombre de valeurs uniques à afficher en aperçu
    max_columns : int | None
        Limiter le nombre de colonnes analysées (None = toutes)
    include_object : bool
        Inclure les colonnes de type object
    include_numeric : bool
        Inclure les colonnes numériques
    """

    cols = df.columns
    if max_columns:
        cols = cols[:max_columns]

    for col in cols:
        dtype = df[col].dtype

        if dtype == "object" and not include_object:
            continue
        if pd.api.types.is_numeric_dtype(dtype) and not include_numeric:
            continue

        total = len(df)
        missing = df[col].isna().sum()
        missing_pct = (missing / total) * 100
        unique_vals = df[col].dropna().unique()

        print("\n-------------------------------------")
        print(f"Colonne : {col}")
        print(f"Type : {dtype}")
        print(f"Valeurs manquantes : {missing_pct:.1f}%")
        print(f"Nombre de valeurs uniques : {len(unique_vals)}")
        print("-------------------------------------")

        display(unique_vals[:max_unique_preview])

#les colonnes object
describe_unique_values(df_listings)

-------------------------------------
Colonne : id
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 59881
-------------------------------------

array([ 2577,  3109,  5396,  7397,  7964,  8522,  9359,  9952, 10010,
       10270])

-------------------------------------
Colonne : listing_url
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 59881
-------------------------------------

array(['https://www.airbnb.com/rooms/2577',
       'https://www.airbnb.com/rooms/3109',
       'https://www.airbnb.com/rooms/5396',
       'https://www.airbnb.com/rooms/7397',
       'https://www.airbnb.com/rooms/7964',
       'https://www.airbnb.com/rooms/8522',
       'https://www.airbnb.com/rooms/9359',
       'https://www.airbnb.com/rooms/9952',
       'https://www.airbnb.com/rooms/10010',
       'https://www.airbnb.com/rooms/10270'], dtype=object)

-------------------------------------
Colonne : scrape_id
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 1
-------------------------------------

array([20181207151406])

-------------------------------------
Colonne : last_scraped
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['2018-12-08', '2018-12-07'], dtype=object)

-------------------------------------
Colonne : name
Type : object
Valeurs manquantes : 0.1%
Nombre de valeurs uniques : 57244
-------------------------------------

array(['Loft for 4 by Canal Saint Martin', 'zen and calm',
       'Explore the heart of old Paris',
       'MARAIS - 2ROOMS APT - 2/4 PEOPLE',
       'Large & sunny flat with balcony !', 'GREAT FLAT w/ CITY VIEW',
       'Cozy, Central Paris: WALK or VELIB EVERYWHERE !',
       'Paris petit coin douillet', 'Paris view from my balcony - B&B',
       'Be charmed by real Paris 11th - B&B'], dtype=object)

-------------------------------------
Colonne : summary
Type : object
Valeurs manquantes : 3.9%
Nombre de valeurs uniques : 56199
-------------------------------------

array(['100 m2 loft (1100 sq feet) with high ceiling, open modern kitchen, cable tv, wifi, sleeping space up to 5 people, Republique area, 5 minutes from the St Martin Canal, Marais area, 10 min from Chatelet and the Louvre.',
       'Appartement très calme de 50M2 Belle lumière Draps et serviettes  Wifi',
       "Cozy, well-appointed and graciously designed studio apartment that mixes old and new aesthetics at the very heart of Paris, on the famous Isle St Louis that is a stone's throw from Le Marais, Quartier Latin, Notre Dame and Le Louvre. ",
       'VERY CONVENIENT, WITH THE BEST LOCATION !',
       'Very large & nice apartment all for you!  - Sunny living room & bedrooms - Well equiped and furnished - Central location & walking distance to many attractions - Great neighborhood',
       'Location! Location! Location! Just bring your toothbrush to this charmingly restored cheerful one bedroom in the center of the city. Exposed beams, facing an interior courtyard, walk to the wonderful rue Montorgeuil market: what else could you want? Brand new renovation, electricity upgrade and new carpet this year. Prefer to rent for a minimum of 6 MONTHS (one year is preferred). Monthly rent discount is 1400 euros.',
       'A real "home from home" in the heart of Paris for up to 4 people (5 with a folding bed)  in an authentic Haussmann apartment with a large balcony.  Close to the main centres of (Website hidden by Airbnb) ideal way to enjoy this fantastic city in complete freedom.',
       'Here you will find a true home from home in Paris so that the Parisian lifestyle will feel part of yours. We will welcome you for a short or medium stay for Bed & Breakfast with the never ending pleasure of sharing Paris with you. Close to metro.',
       'LONG TERM RENTAL Available  The studio is situated on a quiet street and is located on the 4th floor of a 1970’s French apartment building which has a lift and a coded entry.',
       "LONG TERM RENTAL 12 MONTHS  - 9 MONTHS for STUDENTS    The Studio Montmartre 10 is situated on a quiet street and is located on the 2nd and 1/2 floor of a pre-1900's French apartment building which has a coded entry."],
      dtype=object)

-------------------------------------
Colonne : space
Type : object
Valeurs manquantes : 32.3%
Nombre de valeurs uniques : 39554
-------------------------------------

array(['The district has any service or shop you may desire at a walking distance, many restaurants and clubs as well.  I will be pleased to suggest our best addresses and give you directions to have a very enjoyable journey.  We have 1 separated bedroom and one mezzanine for the second bed. One bathroom is "en suite" to the main bedroom.  Welcome to our beautiful loft! Karine',
       'I bedroom appartment in Paris 14',
       'Small, well appointed studio apartment at the very heart of Paris, on the famous Isle St Louis. FOUR-NIGHT MINIMUM.  We are looking for quiet persons or couples to rent our fully equipped and furnished studio (about 30 square meters or 300 square feet) in central Paris on the famous Isle St. Louis. Please contact us for more information. Discounts available for longer stays. The location is superb. Pick up fresh bread at the nearby boulangerie and some exquisite cheese at the local fromagerie for breakfast. Take a late night stroll along the nearby Seine. Bar hop in the adjacent Marais district, the East Village of Paris.',
       'PLEASE ASK ME BEFORE TO MAKE A REQUEST !!! No check-in hour: I do my best ! HEART OF THE HISTORICAL PARIS  Marais, in a securated and classified building, 2d floor, charming 2/3Rooms apt 40 m2, Ideal location in the very heart of historical Paris, metro station: Hôtel-de-Ville, just a few minutes on foot to the Centre Pompidou, Place des Vosges, the Seine River, Notre-Dame Cathedral, the Saint-Louis island... and most of the monuments and museums in Paris. Local restaurants and shops cater to all tastes and budgets. Very charming, quiet, sunny, fully furnished, two bedrooms (one with a large bed, the other with a large and very good sofa/bed), Large bathroom with italian shower. Internet+tel+TV included. Electricity included for normal using. Perfect for one couple, two couples or one couple with one or two children. The apart, at the second floor without lift, reveals the real Paris thanks to its beams and stones.  - one bedroom with a large bed - one living room/bedroom with an excel',
       "hello ! We have a great 75 square meter apartment in the 9e arrondissement. It is  located on a pedestrian street in vibrant neighborhood. You will enjoy a central location : walking distance to Galeries Lafayettes, les Halles, Opéra Garnier, Montmartre. There are lots of typical shops and restaurants around. I'll be glad to advice you on which one to try according to what you like.  3 very close subway stations : Grands Boulevards, Cadet or Notre-Dame de Lorette. It is on the 5th floor, with no elevator. Very sunny with a long balcony : perfect for breakfast or late drink ! One large bedroom with a queen size bed for 2, one room with a double bed, a large sunny living room (Internet wifi, flat screen TV and DVD player). Fully equiped kitchen (washing machine, dishwasher) ; large bathroom with bath ;  Secure building. Do not hesitate to contact me!",
       'Really nice flat located in the 20th district (east) next to the famous Pere Lachaise cimetary (Jim Morrison, Edith Piaf...) with amazing panoramic view over Paris. 7th floor w/ elevator 43 m2, open space living room / bedroom 1 double bed 1 massive couch wich can easely contain one person (or two small ones) 1 kitchen 1 bathroom w/ bathtub 1 dressing room 2 balconies (1 east side over the cimetary park / 1 south side over the city) full of sun all day long, nice for brunch time... Wi-Fi connection. Landline phone with free calls to many other landlines worldwide and free calls to US and Canadian cell phones. Subway station 2 mns walk, going west via center or north (Marais, Opéra, Montmartre Sacré Coeur, Champs Elysées) - Lines 2 and 3. Bus station right in front of the building, going thru the city (Bastille, Marais, Louvre, St Germain, Eiffel Tour) - Line 69. Super market close by. Big commercial street at 5 mn walk. No smoking inside the flat, but you can smoke on the balconies. Am',
       'Since I live in the USA, it is difficult to manage from here, so I am only considering rentals for SIX MONTHS or longer (1 year preferred). Discount for monthly is 1400 euros per month. My home in Paris is as central as you can get....YOU CAN SAVE MONEY by WALKING to everything so you can eat baguettes and chocolate croissants each day: only 5 minutes to the Centre Pompidou, 3 minutes to the Les Halles RER/metro station, 1 minute to the Chatelet metro stop, 5 minutes to the LATE NIGHT bus stop, 10 minutes to Place St. Michel on the other side of the Seine, 10 minutes to the Louvre, 15 minutes to the heart of the old Jewish quarter, Le Marais, 30 minutes to Place des Vosges or St. Germain des Pres, about 30 minutes promenade to galleries in La Bastille, 15 minutes to Notre Dame and the island....you are as central as you can get! My charming apartment is on the fifth floor facing an interior courtyard on one of the busiest streets in Paris, rue St. Denis. There is the Australian bar, OZ',
       "Make your stay in Paris a perfect experience. Our spacious, very French apartements are located in the pleasant 11th Ardonissement just near the Marais between Republique and Bastille. Just 5 minutes from the Picasso Museum, the area has a delightful market, delightful cafés and restaurants. The metro is at your doorstep and it is a pleasant stroll through the Marais down to the river Seine.  The apartment is provided with a computer for email access, a well-equiped kitchen, a double bed, and authentic french furnishings. You will also enjoy the nearby fresh market on Boulevard Richard lenoir with typical French vegetables and fruits in season, fish, meat and many other local produce. Strolling down to Bastille, you can board the wonderful cruises at the Bassin de l'Arsenal right below the Bastille. This will take you on the Canal Saint Martin and below the street level, on to the Parc de La Vilette.",
       'Enjoy a slice of Parisian history and stay in an authentic Haussmann apartment. Sleeping up to five people, it is a charming apartment (50 m²) with parquet floors, mouldings and a fireplace with two adjoining bedrooms, a fully equipped kitchen and a large balcony decorated with flowers. On the 5th floor without a lift, appreciate the clear view of Paris and get excited by how central this apartment is to so many attractions. A short walk away are three Metro stations with numerous connections to the main line RER, airport, taxi and bus stations nearby. The movida room : An association of clear bright colours lightens this room with a design decoration just a touch psychedelic to recall the sensual and slightly kitsch ambiance of the films of Pedro Almodovar....But it’s only an unpretentious nod and a wink !  Associated with an old fashioned setting of mouldings, parquet floor and fireplace the overall effect comes across as rather appealing... judge for yourself. With it’s two single b',
       'Here you will find a true home from home so that the Parisian lifestyle will feel part of yours.The apartment is situated on the second floor (without a lift) of this three floored building. The low rise nature of the building gives it a human dimension much appreciated and rare in the heart of the Capital. The apartment has a kitchen/diner, a living room with a double sofa bed, a bedroom with 2 single beds (which can be put together to make a double bed), and a bathroom. The apartment has been entirely renovated and has been redecorated by ourselves in a ‘seventies style…..We’ve put a lot of enthusiasm into it and we hope you’ll love it. The building, built in the eighteenth century, was not originally residential but built to house metal-working facilities in a working class neighbourhood of the Capital. This activity has given the name to the “Passage de Fonderie (Foundry Passage)” that leads to the building. This preserved passageway has kept all of it’s charm with it’s cobbles, th'],
      dtype=object)

-------------------------------------
Colonne : description
Type : object
Valeurs manquantes : 0.8%
Nombre de valeurs uniques : 58583
-------------------------------------

array(['100 m2 loft (1100 sq feet) with high ceiling, open modern kitchen, cable tv, wifi, sleeping space up to 5 people, Republique area, 5 minutes from the St Martin Canal, Marais area, 10 min from Chatelet and the Louvre. The district has any service or shop you may desire at a walking distance, many restaurants and clubs as well.  I will be pleased to suggest our best addresses and give you directions to have a very enjoyable journey.  We have 1 separated bedroom and one mezzanine for the second bed. One bathroom is "en suite" to the main bedroom.  Welcome to our beautiful loft! Karine Metro lines : 4, 8, 3, 11, 9.',
       'I bedroom appartment in Paris 14',
       "Cozy, well-appointed and graciously designed studio apartment that mixes old and new aesthetics at the very heart of Paris, on the famous Isle St Louis that is a stone's throw from Le Marais, Quartier Latin, Notre Dame and Le Louvre. Small, well appointed studio apartment at the very heart of Paris, on the famous Isle St Louis. FOUR-NIGHT MINIMUM.  We are looking for quiet persons or couples to rent our fully equipped and furnished studio (about 30 square meters or 300 square feet) in central Paris on the famous Isle St. Louis. Please contact us for more information. Discounts available for longer stays. The location is superb. Pick up fresh bread at the nearby boulangerie and some exquisite cheese at the local fromagerie for breakfast. Take a late night stroll along the nearby Seine. Bar hop in the adjacent Marais district, the East Village of Paris. The flat includes its own modern bathroom, a washing machine, stove, oven, toaster and coffee press. For sleeping there is only a fold-o",
       'VERY CONVENIENT, WITH THE BEST LOCATION ! PLEASE ASK ME BEFORE TO MAKE A REQUEST !!! No check-in hour: I do my best ! HEART OF THE HISTORICAL PARIS  Marais, in a securated and classified building, 2d floor, charming 2/3Rooms apt 40 m2, Ideal location in the very heart of historical Paris, metro station: Hôtel-de-Ville, just a few minutes on foot to the Centre Pompidou, Place des Vosges, the Seine River, Notre-Dame Cathedral, the Saint-Louis island... and most of the monuments and museums in Paris. Local restaurants and shops cater to all tastes and budgets. Very charming, quiet, sunny, fully furnished, two bedrooms (one with a large bed, the other with a large and very good sofa/bed), Large bathroom with italian shower. Internet+tel+TV included. Electricity included for normal using. Perfect for one couple, two couples or one couple with one or two children. The apart, at the second floor without lift, reveals the real Paris thanks to its beams and stones.  - one bedroom with a large b',
       "Very large & nice apartment all for you!  - Sunny living room & bedrooms - Well equiped and furnished - Central location & walking distance to many attractions - Great neighborhood hello ! We have a great 75 square meter apartment in the 9e arrondissement. It is  located on a pedestrian street in vibrant neighborhood. You will enjoy a central location : walking distance to Galeries Lafayettes, les Halles, Opéra Garnier, Montmartre. There are lots of typical shops and restaurants around. I'll be glad to advice you on which one to try according to what you like.  3 very close subway stations : Grands Boulevards, Cadet or Notre-Dame de Lorette. It is on the 5th floor, with no elevator. Very sunny with a long balcony : perfect for breakfast or late drink ! One large bedroom with a queen size bed for 2, one room with a double bed, a large sunny living room (Internet wifi, flat screen TV and DVD player). Fully equiped kitchen (washing machine, dishwasher) ; large bathroom with bath ;  Secure",
       'Really nice flat located in the 20th district (east) next to the famous Pere Lachaise cimetary (Jim Morrison, Edith Piaf...) with amazing panoramic view over Paris. 7th floor w/ elevator 43 m2, open space living room / bedroom 1 double bed 1 massive couch wich can easely contain one person (or two small ones) 1 kitchen 1 bathroom w/ bathtub 1 dressing room 2 balconies (1 east side over the cimetary park / 1 south side over the city) full of sun all day long, nice for brunch time... Wi-Fi connection. Landline phone with free calls to many other landlines worldwide and free calls to US and Canadian cell phones. Subway station 2 mns walk, going west via center or north (Marais, Opéra, Montmartre Sacré Coeur, Champs Elysées) - Lines 2 and 3. Bus station right in front of the building, going thru the city (Bastille, Marais, Louvre, St Germain, Eiffel Tour) - Line 69. Super market close by. Big commercial street at 5 mn walk. No smoking inside the flat, but you can smoke on the balconies. Am',
       'Location! Location! Location! Just bring your toothbrush to this charmingly restored cheerful one bedroom in the center of the city. Exposed beams, facing an interior courtyard, walk to the wonderful rue Montorgeuil market: what else could you want? Brand new renovation, electricity upgrade and new carpet this year. Prefer to rent for a minimum of 6 MONTHS (one year is preferred). Monthly rent discount is 1400 euros. Since I live in the USA, it is difficult to manage from here, so I am only considering rentals for SIX MONTHS or longer (1 year preferred). Discount for monthly is 1400 euros per month. My home in Paris is as central as you can get....YOU CAN SAVE MONEY by WALKING to everything so you can eat baguettes and chocolate croissants each day: only 5 minutes to the Centre Pompidou, 3 minutes to the Les Halles RER/metro station, 1 minute to the Chatelet metro stop, 5 minutes to the LATE NIGHT bus stop, 10 minutes to Place St. Michel on the other side of the Seine, 10 minutes to th',
       "Make your stay in Paris a perfect experience. Our spacious, very French apartements are located in the pleasant 11th Ardonissement just near the Marais between Republique and Bastille. Just 5 minutes from the Picasso Museum, the area has a delightful market, delightful cafés and restaurants. The metro is at your doorstep and it is a pleasant stroll through the Marais down to the river Seine.  The apartment is provided with a computer for email access, a well-equiped kitchen, a double bed, and authentic french furnishings. You will also enjoy the nearby fresh market on Boulevard Richard lenoir with typical French vegetables and fruits in season, fish, meat and many other local produce. Strolling down to Bastille, you can board the wonderful cruises at the Bassin de l'Arsenal right below the Bastille. This will take you on the Canal Saint Martin and below the street level, on to the Parc de La Vilette. Cet appartement n est pas accessible aux Handicapés.. logement ancien et petit...",
       'A real "home from home" in the heart of Paris for up to 4 people (5 with a folding bed)  in an authentic Haussmann apartment with a large balcony.  Close to the main centres of (Website hidden by Airbnb) ideal way to enjoy this fantastic city in complete freedom. Enjoy a slice of Parisian history and stay in an authentic Haussmann apartment. Sleeping up to five people, it is a charming apartment (50 m²) with parquet floors, mouldings and a fireplace with two adjoining bedrooms, a fully equipped kitchen and a large balcony decorated with flowers. On the 5th floor without a lift, appreciate the clear view of Paris and get excited by how central this apartment is to so many attractions. A short walk away are three Metro stations with numerous connections to the main line RER, airport, taxi and bus stations nearby. The movida room : An association of clear bright colours lightens this room with a design decoration just a touch psychedelic to recall the sensual and slightly kitsch ambiance ',
       'Here you will find a true home from home in Paris so that the Parisian lifestyle will feel part of yours. We will welcome you for a short or medium stay for Bed & Breakfast with the never ending pleasure of sharing Paris with you. Close to metro. Here you will find a true home from home so that the Parisian lifestyle will feel part of yours.The apartment is situated on the second floor (without a lift) of this three floored building. The low rise nature of the building gives it a human dimension much appreciated and rare in the heart of the Capital. The apartment has a kitchen/diner, a living room with a double sofa bed, a bedroom with 2 single beds (which can be put together to make a double bed), and a bathroom. The apartment has been entirely renovated and has been redecorated by ourselves in a ‘seventies style…..We’ve put a lot of enthusiasm into it and we hope you’ll love it. The building, built in the eighteenth century, was not originally residential but built to house metal-wor'],
      dtype=object)

-------------------------------------
Colonne : experiences_offered
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 1
-------------------------------------

array(['none'], dtype=object)

-------------------------------------
Colonne : neighborhood_overview
Type : object
Valeurs manquantes : 40.5%
Nombre de valeurs uniques : 32885
-------------------------------------

array(['You are within walking distance to the Louvre, Notre Dame, Le Marais, Les Halles, Chatelet, St. Germain, Les Tuileries, le Jardin des Plantes, St. Michel, Sorbonne, Institut du Monde Arab, the Bastille and the Latin Quarter.  ',
       'This area typically Parisian, is nice, trendy and popular with, near the rue Oberkampf and its restaurants, bars, shops ... what to spend your evenings in the festive atmosphere. Also near the City Hall and the Marais district, the oldest district of Paris is also known for its "gay life". Still near the Canal Saint Martin now so characteristic of "Paris bobo" or you end up on Sunday for a picnic with friends, rollerblading or cycling ... Canal where you can also navigate a real curiosity The boulevard that stretches from the Place de la Bastille to the canal Saint Martin passing under your balcony gives oxygen and greenery with tall trees and colorful flower beds. It is also a lively area with the market very closeby (every Tuesday and Friday morning), its flea markets, and petanque players place. Near the apartment many shops, supermarkets, restaurants, bars, theaters, discos, cultural sites, services ... You can move by feet or by public transport and easy access to all tourist attr',
       'This area typically Parisian, is nice, trendy and popular with, near the rue Oberkampf and its restaurants, bars, shops ... what to spend your evenings in the festive atmosphere. Also near the City Hall and the Marais district, the oldest district of Paris is also known for its "gay life". Still near the Canal Saint Martin now so characteristic of "Paris bobo" or you end up on Sunday for a picnic with friends, rollerblading or cycling ... Canal where you can also navigate a real curiosity  It is also a lively area with the market very closeby (every Tuesday and Friday morning), its flea markets, and petanque players place. Near the apartment many shops, supermarkets, restaurants, bars, theaters, discos, cultural sites, services ... You can move by feet or by public transport and easy access to all tourist attractions that dot the capital, Eiffel Tower Montmartre, Notre Dame to the Champs Elysees, Invalides at Parc de la Villette, Pere Lachaise at the Louvre, without forgetting the Sein',
       'Montmartre, the neighborhood surrounding the studio, maintains its physical charm and the village atmosphere remains remarkably intact. True montmartrians however, use their feet to visit the area. This is the perfect way to enjoy the unique architecture of the area: there are tiny exquisite squares, wooden houses, hidden parks, winding streets, small terraces and long stairways plus the Butte’s famous vineyard.  Many shops and stores are close to the apartment: bakery, butcher, supermarkets, restaurants, cafes, clubs, laundromats, and doctors.',
       "Nous sommes dans le quartier de Belleville, entre le Marais et le parc des Buttes-Chaumont. A dix minutes en métro de Châtelet, à 15 minutes de l'Opéra ou de Montmartre. / Location : Belleville area (Between le Marais and the Buttes-Chaumont park). The flat is 10min away by subway from Châtelet, 15 minutes from the Opéra or Montmartre.",
       'The apartment is located at the foot of charming Butte Montmartre. This historical area has now become truly « bourgeois bohême » with fashionable boutiques, galleries and young creators workshops.  But it has kept its old charm, with small steep streets and pretty cobbled squares, and its artistic soul, that which was born in the 19th century when Van Gogh, Toulouse Lautrec, Picasso, Modigliani, installed their easels inspired by the places. More recently it was the frame of many movies among which  « Le Fabuleux Destin d’Amélie Poulain ». It is like a village in the heart of Paris. Montmartre is also unique for entertainment. Within 500 meters from the appartment are some of Paris most sought after places : - le Sacré Cœur, 370 m - le Moulin Rouge, 550 m - le Moulin de la Galette, 300 m - le cabaret Michou, 150 m - les Vignes de Montmartre, 500 m - concert hall la Cigale, 200 m Also in the vicinity, are : - 2 theaters, le Théâtre Charles Dullin, 200m, et le Théâtre des Abbesses, 75 m',
       'Near china town and very convenient to be quickly in the center of the city with thesubway line 14.',
       "Le 11e est un ancien quartier d'artisans, avec beaucoup de cours intérieures qui en font le charme. Ce quartier s'embourgeoise depuis 30 ans. Notre immeuble est classé (ancien immeuble où a vécu Parmentier). Quartier animé et commerçant. Vous pouvez rentrer tard le soir en toute sécurité. Tous les commerces et restaurants sont situés à proximité. Quartier central, proche de tous les transports.",
       'I will send you via email all the required details to come home depending on the location of your arrival (train station, airport, other)',
       "The studio is without any doubt located in one of the greatest and most pleasant Parisian area.  There are so many great restaurants, café, brasseries, wine marchants and other somptuous shops. This would also be forgetting the Sacré-Coeur, reachable in less than ten minutes by walk, and some of the best-known Parisian places (think of Le Moulin Rouge, Pigalle, Amélie Poulain...) It's simply one of the most pleasant and living neighborhood of Paris."],
      dtype=object)

-------------------------------------
Colonne : notes
Type : object
Valeurs manquantes : 68.9%
Nombre de valeurs uniques : 16209
-------------------------------------

array(['The staircase leading up to the apartment is narrow and old -- this is a very old building, so perhaps unsuitable for those with difficulty walking or climbing up stairs.',
       'Important: Be conscious that an apartment in a building of the old Paris is not an apartment in a tower of Singapore... If you do not, please do not make a request! I rent easily this place and I prefer to welcome open minded guests!',
       'Velib station outside.',
       "We participated in the very beginning of the Airbnb'adventure  in Paris in 2009 and I had the pleasure to spend a day with Joe, one of the founders, who photographed the apartment by himself. I doubt he does that again today !!! I keep a very pleasant memory of this day and I am admiring the way traveled by Airbnb with whom I hope to continue a long way.",
       "Important remarks / Remarques importantes    When rented, the flat can accomodate for up to six guests, which is no small amount for a 65 m2 flat. My purpose is to help people traveling in groups to stay together in the same place during their stay in Paris for an rather affordable fare.  This is a very-appreciated plus for lots of travellers. Yet, albeit rarely, some travellers write comments with complaints about the lack of space for six in the flat. So please check carefully the space described in the ad and keep in mind that when 4 people sleep in the living room, this living room inevitably looks crammed with things (beds, suitcases). A bit like camping in a way.  Yet, the vast majority of guests enjoy the flat like this. But in case of doubt about the space thus proposed, do not rent. Keep in mind your comfort as a guest comes first. / En mode location, l’appartement accueille jusqu'à six personnes, ce qui n'est pas rien dans un appartement de 65 m2. Il s'agit d'une volonté de m",
       'Folding baby bed available.',
       "L'appartement est prévu pour 4 personnes maximum. Cet appartement est ma résidence principale. Veuillez en prendre soin comme chez vous.",
       "Don't hesitate to ask us for our favorite and confidential places, we will share them with joy. Cleaning is included in the price. Bed linen and towels are provided.",
       "Please don't make a reservation request without first having contacted me, as I will never accept one without having had some initial contact with you.",
       'Please read carefully the ad, all details are there and if any question, ask me!'],
      dtype=object)

-------------------------------------
Colonne : transit
Type : object
Valeurs manquantes : 36.3%
Nombre de valeurs uniques : 36492
-------------------------------------

array(['Metro lines : 4, 8, 3, 11, 9.', 'ligne 13 and RER B, Ligne 4',
       "The flat is close to two or three major metro lines, as well near several of Paris' Velibre stations where you can rent a bike for a small fee.",
       'Metro station HÖTEL-DE-VILLE is 100 meters close.',
       'All the major metros and RERs are at Les Halles or Chatelet. Very easy to arrive and the night buses are also nearby at Hotel de Ville, 5 minutes away walking. Velib in front of building!',
       'I can also organize transport service.Easy access from the train stations and airports. I am in contact with you as soon as your booking is made and I provide you with accurate information access to the apartment. One minute to metro station Saint Ambroise line 9 makes traveling by metro very easy. Many connections with the main axes RER, SNCF, Airports ... Taxi and Bus Station nearby. Bike rental, the Vélibs so pleasant  ...',
       'Easy access from the train stations and airports. I am in contact with you as soon as your booking is made and I provide you with accurate information access to the apartment. I can also organize transport service. Less than 5 minutes to metro station Parmentier and many lines that make traveling by metro very easy. Many connections with the main axes RER, SNCF, Airports ... Taxi and Bus Station nearby. Bike rental, the Vélibs so pleasant  ...',
       "The studio can be easily accessed by the RER, Metro, bus or taxi from Charles De Gaule airport or any Paris train station (if traveling to Paris by train from another European destination). Detail information will be provided to you prior to your arrival via email or fax. METRO:  Métro station Château Rouge (line 4), Marcadet-Poissonniers (line4) or Jules Joffrin (line 12) are just a 10-15 minutes walk away.  BUS:  Bus n°85 goes to the center of Paris Châtelet, Les Halles (many shops) and Le Louvre, Luxembourg garden.  Bus n° 80 goes to Place de Clichy (Pathé Cinéma theatre, restaurants...), Saint-Lazarre station, the Champs Elysées, Pont d'Alma, the Eiffel Tower.  The Montmartrobus is a fantastic way to get around Montmartre (Sacré-Coeur, Place du Tertre, Pigalle) without exhausting yourself climbing up and down those hills! BIKES: You can also find bike stands: Vélib’ which is a self service 'bike hire' system available 24 hours a day, 7 days a week. Multi pick up and drop off locati",
       "  The studio can be easily accessed by the RER, Metro, bus or taxi from Charles De Gaule airport or any Paris train station (if traveling to Paris by train from another European destination). Detail information will be provided to you prior to your arrival via email or fax. METRO:  Métro station Château Rouge (line 4), Marcadet-Poissonniers (line4) or Jules Joffrin (line 12) are just a (Phone number hidden by Airbnb) minutes walk away.  BUS:  Bus n°85 goes to the center of Paris Châtelet, Les Halles (many shops) and Le Louvre, Luxembourg garden.  Bus n° 80 goes to Place de Clichy (Pathé Cinéma theatre, restaurants...), Saint-Lazarre station, the Champs Elysées, Pont d'Alma, the Eiffel Tower.  The Montmartrobus is a fantastic way to get around Montmartre (Sacré-Coeur, Place du Tertre, Pigalle) without exhausting yourself climbing up and down those hills! BIKES: You can also find bike stands: Vélib’ which is a self service 'bike hire' system available 24 hours a day, 7 days a week. Multi",
       'Closest Métro stations : Belleville (Lines 2 and 11) and Goncourt (Lines 11)'],
      dtype=object)

-------------------------------------
Colonne : access
Type : object
Valeurs manquantes : 51.8%
Nombre de valeurs uniques : 22648
-------------------------------------

array(["The flat includes its own modern bathroom, a washing machine, stove, oven, toaster and coffee press. For sleeping there is only a fold-out couch but it has a real mattress that's rather comfortable. There is a desk that's excellent for working, bar stools, a fully-equipped kitchenette, television, closet space, wireless broadband internet, towels, linens, pots, pans, plates, forks, knives.  All you need to bring are your clothes and toothbrush. Excellent for visiting scholars, businesspersons or tourists. Absolutely no pets or smoking allowed.  ",
       'You have access to all the apartment.',
       "You are alone in the flat, the entire city is at your feet. You will enjoy being able to go outside and be astonished at the liveliness of the area and then come back home and it's facing two courtyards so there is a calm which helps make being in the center attractive.",
       'Cet appartement n est pas accessible aux Handicapés.. logement ancien et petit...',
       'Services and equipment :  free wireless internet high speed, ADSL, large LCD TV, DVD, free phone to numerous countries, bed linen and towels, hairdryer, safe box, baby cot, stroller, equipped kitchen, dishes, small and large appliances including dishwasher...).  Breakfast is provided on a do it yourself basis (tea, coffee, drinking chocolate, milk, orange juice, toast bread, brioche, butter, “home-made” jam, cereals, yoghurts). Guides and city maps are also available.',
       'The price includes : Breakfast provided to prepare yourself freely (tea, coffee, hot chocolate, milk, orange juice, toast bread, brioche, butter, home-made jam, cereals, yoghurt…)  fresh bedding and bath towels  maid service at the end of the stay  use of all available facilities (internet high speed, Wi-Fi access, TV with many international channels, DVD player, free phone to many countries)  baby cot, safe box, choice of DVD’s, maps and guides of Paris...',
       'There is a phone with free calls in France and free calls for abroad (for some countries, ask for more details). You also have an internet connection (wifi or USB cable), television, DVD player (Zone 2: will not play US DVDs), iron and ironing board, closet space as well as a small table and four chairs.',
       ' There is a telephone with free calls in France to fixed line phones and free long distance calls (for some countries-ask for more details). You also have an internet connection (Wi-Fi or USB cable), television, DVD player (Zone 2: will not play US DVDs), iron and ironing board, closet space as well as a small table and four chairs.  No Smoking. No pets.',
       "Renters have access to the full flat /Les voyageurs ont accès à tout l'appartement.",
       'TV Wifi Fridge '], dtype=object)

-------------------------------------
Colonne : interaction
Type : object
Valeurs manquantes : 52.6%
Nombre de valeurs uniques : 24322
-------------------------------------

array(['yes I can help you out',
       'We expect guests to operate rather independently, though we welcome questions about the flat and urge you to call us immediately if there is any kind of emergency or trouble.',
       'We are there to welcome you, give you keys and advice you on great places to eat & drink around.',
       "I am available 18 hours a day by text, have lots of friends (and friendly neighbors) in Paris available to help answer any questions. It's easy to rent with me. Like having your family flat for your personal use!",
       'I welcome you personally on your arrival, I give you all the useful information to make the most of the apartment and its facilities and I give you the services and shops of the neighborhood. Throughout your stay you can ask me because I live next door.',
       'I welcome you personally upon arrival, I give you all the information to get the most of the apartment and its facilities and I tell you the services and boutiques in the area. All through your stay you can ask me because I live nearby.',
       'I am always happy to help with advice and suggestions. I can be joined by phone if not physically available). / Je suis toujours disponible pour toute question avant, pendant et après le séjour. Je suis joignable par téléphone quand je ne suis pas physiquement présent.',
       'As soon as reservation firm, I will give all the details to get in touch with me and solve any problem that might happen. Professional support will be available for your check in and stay.',
       'At the begining to explain everything!',
       'I do my best to answer to all the questions of my guests, in order to make their stay in Paris smooth and enjoyable'],
      dtype=object)

-------------------------------------
Colonne : house_rules
Type : object
Valeurs manquantes : 52.4%
Nombre de valeurs uniques : 23463
-------------------------------------

array(['This is a small flat in a very old building that we also use when the two of us and our infant daughter come to Paris. We ask that you treat the flat as if it were your own place, and leave it reasonably tidy when you leave. No smoking or pets. Please remember to double lock the door when you step out.',
       "ELECTRICITY INCLUDED FOR NORMAL USING. PLEASE TURN OFF LIGHTS AND HEATING EACH TME YOU LEAVE IMPORTANT FOR TRASH : RESPECT THE SELECTIVE SORTING !  AND DON'T BE NOISY IN THE STAIRS WITH BAGS !",
       'Respect.',
       'This residence is limited to TWO people and is for a MINIMUM rental of SIX MONTHS.',
       'DO NOT USE FIREPLACE',
       'You are feeling free in your home away from home.  The occupation of the apartment must be respecting the neighbors.  Information to become familiar with the apartment and its surroundings will be given on arrival. We are closeby for the duration of your stay to assist you if necessary. We are happy to help you if you need assistance (need to print documents, book a tour or a show, call for a taxi...) . It is forbidden to smoke in the apartment but smoking is permitted on the balcony',
       "When you are in this apartment and you are home free. Obviously you must respect the place and the neighbors On arrival I will give you some guidelines so that all goes well and you will soon feel at home. That's what all the people who have stayed there say. We live 5 minutes away and we are easily reachable by phone. We can easily respond to any problems, breakdown or if you need assistance (need to print documents, book a tour or a show, call for a taxi...) It is forbidden to smoke in the apartment",
       "Sanibroyeur neuf dans la salle d'eau : ne rien jeter à part papier hygiénique : sinon, coût de la réparation : 600 € !!!",
       'For the week-ends the check-in has to be after 1 p.m on Friday. On Monday, the check-out has to be before 10.30 a.m. Some arrangments can be founded for the luggage.  The cleaning must be done before leaving. At the inscription, I mail  informations for using the studio, and advices for good addresses in the area. During the summer holidays, a stay of 4 nights minimum is requested.',
       'out of respect for the next renters and the owner, respect the place'],
      dtype=object)

-------------------------------------
Colonne : thumbnail_url
Type : float64
Valeurs manquantes : 100.0%
Nombre de valeurs uniques : 0
-------------------------------------

array([], dtype=float64)

-------------------------------------
Colonne : medium_url
Type : float64
Valeurs manquantes : 100.0%
Nombre de valeurs uniques : 0
-------------------------------------

array([], dtype=float64)

-------------------------------------
Colonne : picture_url
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 59680
-------------------------------------

array(['https://a0.muscache.com/im/pictures/09da057c-0120-4d5c-b464-d95c75921dde.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/baeae9e2-cd53-4ac3-b1bc-4055c0bb2e77.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/52413/f9bf76f5_original.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/67928287/330bd78c_original.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/4471349/6fb3de47_original.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/30560/08769a1a_original.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/c2965945-061f-4ad8-a547-d617e5781827.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/52474/aeb7de2a_original.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/1d8c4fb5-ac66-4140-871a-0f558fb9f280.jpg?aki_policy=large',
       'https://a0.muscache.com/im/pictures/86310660/d86f0c24_original.jpg?aki_policy=large'],
      dtype=object)

-------------------------------------
Colonne : xl_picture_url
Type : float64
Valeurs manquantes : 100.0%
Nombre de valeurs uniques : 0
-------------------------------------

array([], dtype=float64)

-------------------------------------
Colonne : host_id
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 51336
-------------------------------------

array([ 2827,  3631,  7903,  2626, 22155, 25435, 28422, 33534, 33995,
       37107])

-------------------------------------
Colonne : host_url
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 51336
-------------------------------------

array(['https://www.airbnb.com/users/show/2827',
       'https://www.airbnb.com/users/show/3631',
       'https://www.airbnb.com/users/show/7903',
       'https://www.airbnb.com/users/show/2626',
       'https://www.airbnb.com/users/show/22155',
       'https://www.airbnb.com/users/show/25435',
       'https://www.airbnb.com/users/show/28422',
       'https://www.airbnb.com/users/show/33534',
       'https://www.airbnb.com/users/show/33995',
       'https://www.airbnb.com/users/show/37107'], dtype=object)

-------------------------------------
Colonne : host_name
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 10038
-------------------------------------

array(['Karine', 'Anne', 'Borzou', 'Franck', 'Anaïs', 'Adrien',
       'Bernadette', 'Elisabeth', 'Pascal', 'Michael'], dtype=object)

-------------------------------------
Colonne : host_since
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 3140
-------------------------------------

array(['2008-09-09', '2008-10-14', '2009-02-14', '2008-08-30',
       '2009-06-18', '2009-07-13', '2009-07-29', '2009-08-24',
       '2009-08-26', '2009-09-08'], dtype=object)

-------------------------------------
Colonne : host_location
Type : object
Valeurs manquantes : 0.3%
Nombre de valeurs uniques : 2097
-------------------------------------

array(['Casablanca, Grand Casablanca, Morocco',
       'Paris, Île-de-France, France', 'Istanbul, İstanbul, Turkey',
       'Paris, Ile-de-France, France',
       'New York, New York, United States', 'France', 'Vietnam',
       'Paris and venice Beach', 'Longjumeau, Ile-de-France, France',
       'Madrid, Community of Madrid, Spain'], dtype=object)

-------------------------------------
Colonne : host_about
Type : object
Valeurs manquantes : 49.3%
Nombre de valeurs uniques : 24075
-------------------------------------

array(["Arrivée à Casablanca il y a 4 ans, je suis amoureuse de cette ville méconnue des visiteurs hors voyage d'affaire. ",
       "We are both journalists based in the Middle East, and spend a lot of time traveling for work, so we understand what people need when they're away from home. Delphine is Parisian -- her aunt helps us rent out the apartment. We both love Paris and try to make it easy for people to come and visit the city. ",
       'I am a writer,51, author of novels, books of linguistics...',
       'Hello ! \r\nOur apartment is great and I am sure you will love it ! I will be happy to share with you tips and my favourites places to make your stay super nice.',
       'De Paris, propre et organisé.',
       'I am a Native New Yorker (yes, I was born and raised here!) and have lived in Boston, Paris and Los Angeles and speak a bit of French and Spanish and about two words of Italian. I work in the legal field. I went to culinary school to study pastry many years ago and now I just bake cookies at Christmas when I have the time!\r\n\r\nI have traveled to over 60 countries, go away to my house in Pennsylvania on many weekends and like meeting new people. \r\n\r\nAs to the listings on AIRBNB: I have one "Supersize Studio" on the Upper East Side, which is a walk-up and has no doorman and I do not live there. The building is approximately 50 years old. The entire apartment is at your disposal. There is a queen sized bed, a table and chairs and it is perfect for a sole occupant needing a home-away-from-home. It is in Yorkville, home of the old Austrian and Hungarian and German bakeries, long gone. On Saturdays, at Saint Stephen\'s, which is opposite the apartment, there is a market which is wonderful. Otherwise, you have more than enough small cute places  to eat and hang out and if you are a couple of young single people, all the bars and restaurants you might want to go to until closing are on Second Avenue, one block over. This apartment is a very large studio with high ceilings and faces north to a garden, which is quiet. It comes with linens and dishes and has a small kitchen. There is a $60 cleaning fee and a $500security deposit required. AIRBNB collects the security and I ask you pre-pay the cleaning fee on arrival in cash.\r\n\r\nSo as to avoid confusion, the second listing, "Paris in New York" location is my home and about which I speak below and this is the apartment which has been reviewed the most. I no longer allow it to be rented.\r\n\r\nI traveled to Europe the first time on my own via SERVAS many years ago and have not forgotten the kindness of the people I met then. I hope to reciprocate and make new friends!\r\n\r\nPlease contact me if you are interested in staying at one of my places. You MUST be a non-smoker but smoking is allowed in front of the building outside if you are desperate.\r\n\r\nPlease have your profile here. It is easier if I know  something about who you are, where you live and what you do. If I don\'t know something about you, it\'s hard for me to answer a request to stay quickly, since I like to have a level of comfort renting.\r\n\r\nI\'ve known one friend who lives in Abu Dhabi who I met via SERVAS over 30 years now. I expect to know my AirBNB guests just as long!\r\n\r\nThanks for your interest!\r\n\r\nAs to the other listings: the apartment in Paris (Chatelet) is not available again until 2015.  It is rented a minimum of six months. The apartment in Hossegor, in the Southwest of France, is available off-season each year from October until May. \r\n\r\nThe Victorian house in northeast Pennsylvania is available on select weeks if you are interested in skiing at Elk Mountain, which is 20 minutes up the hill on Route 106 from Carbondale.\r\n\r\nJust ask me!\r\n\r\n\r\n',
       'Parisienne retraitée, dynamique et accueillante, Elisabeth vous attend dans son petit nid au coeur des quartiers animés de Bastille et de République plein de restaurants typiques .Vous y serez "at home" avec toutes les facilités pour un séjour "cosy".\r\nA deux pas du Marais, vous pourrez le parcourir à pied facilement, de belles promenades en perspective....\r\nElisabeth, a true parisian, dynamic and welcoming, is expecting you in her "nest" in Bastille and République busy area, full of typical restaurants. You will feel at home in her cosy place. Within a walking distance from the Marais district, a lot of "promenades" to enjoy...',
       'Welcome in Paris! I enjoy traveling and sharing my insider tips about Paris. I have traveled Australia, South America, US, Asia,  Egypt, Africa, Europe,..... and I am one of the very first Airbnb host in Paris!',
       'Licensed California Architect living in Paris\r\nI am a AIA member\r\n\r\nFeel free to contact me If you have any questions\r\n',
       "I'll be very glad to welcome you in my little apartment in Paris ! Even if I work very hard, I'll try to help you to discover the town and to give you advice!"],
      dtype=object)

-------------------------------------
Colonne : host_response_time
Type : object
Valeurs manquantes : 48.3%
Nombre de valeurs uniques : 4
-------------------------------------

array(['within a day', 'within an hour', 'within a few hours',
       'a few days or more'], dtype=object)

-------------------------------------
Colonne : host_response_rate
Type : object
Valeurs manquantes : 48.3%
Nombre de valeurs uniques : 75
-------------------------------------

array(['75%', '100%', '86%', '80%', '90%', '50%', '0%', '97%', '74%',
       '63%'], dtype=object)

-------------------------------------
Colonne : host_acceptance_rate
Type : float64
Valeurs manquantes : 100.0%
Nombre de valeurs uniques : 0
-------------------------------------

array([], dtype=float64)

-------------------------------------
Colonne : host_is_superhost
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['f', 't'], dtype=object)

-------------------------------------
Colonne : host_thumbnail_url
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 51164
-------------------------------------

array(['https://a0.muscache.com/im/pictures/17fe6c88-a480-4a63-bfa7-1c0951105958.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/3631/profile_pic/1375800198/original.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/7903/profile_pic/1280002723/original.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/pictures/58f00c4d-f805-4605-9f7c-5c848814c828.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/22155/profile_pic/1271497205/original.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/25435/profile_pic/1259111394/original.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/28422/profile_pic/1319547089/original.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/pictures/user/4f775bb4-9080-4943-aa57-d516708aec81.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/33995/profile_pic/1392889357/original.jpg?aki_policy=profile_small',
       'https://a0.muscache.com/im/users/37107/profile_pic/1333994771/original.jpg?aki_policy=profile_small'],
      dtype=object)

-------------------------------------
Colonne : host_picture_url
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 51164
-------------------------------------

array(['https://a0.muscache.com/im/pictures/17fe6c88-a480-4a63-bfa7-1c0951105958.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/3631/profile_pic/1375800198/original.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/7903/profile_pic/1280002723/original.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/pictures/58f00c4d-f805-4605-9f7c-5c848814c828.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/22155/profile_pic/1271497205/original.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/25435/profile_pic/1259111394/original.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/28422/profile_pic/1319547089/original.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/pictures/user/4f775bb4-9080-4943-aa57-d516708aec81.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/33995/profile_pic/1392889357/original.jpg?aki_policy=profile_x_medium',
       'https://a0.muscache.com/im/users/37107/profile_pic/1333994771/original.jpg?aki_policy=profile_x_medium'],
      dtype=object)

-------------------------------------
Colonne : host_neighbourhood
Type : object
Valeurs manquantes : 14.4%
Nombre de valeurs uniques : 247
-------------------------------------

array(['République', 'Alésia', 'Saint-Paul - Ile Saint-Louis',
       'Le Marais', "Gare du Nord - Gare de I'Est",
       'Père Lachaise - Ménilmontant',
       'Châtelet - Les Halles - Beaubourg', 'Montmartre', 'Saint-Lazare',
       'Panthéon'], dtype=object)

-------------------------------------
Colonne : host_listings_count
Type : float64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 83
-------------------------------------

array([ 2.,  1.,  3.,  6.,  4., 14.,  7., 83.,  5., 54.])

-------------------------------------
Colonne : host_total_listings_count
Type : float64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 83
-------------------------------------

array([ 2.,  1.,  3.,  6.,  4., 14.,  7., 83.,  5., 54.])

-------------------------------------
Colonne : host_verifications
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 451
-------------------------------------

array(["['email', 'phone', 'reviews', 'jumio', 'government_id']",
       "['email', 'phone', 'facebook', 'reviews']",
       "['email', 'phone', 'facebook', 'google', 'reviews', 'jumio', 'government_id']",
       "['email', 'phone', 'reviews', 'jumio', 'offline_government_id', 'selfie', 'government_id', 'identity_manual']",
       "['email', 'phone', 'reviews', 'jumio', 'offline_government_id', 'government_id']",
       "['email', 'phone', 'reviews']",
       "['email', 'phone', 'manual_online', 'facebook', 'reviews', 'manual_offline', 'jumio', 'offline_government_id', 'selfie', 'government_id', 'identity_manual', 'work_email']",
       "['email', 'phone', 'facebook', 'reviews', 'jumio', 'government_id']",
       "['email', 'phone', 'reviews', 'offline_government_id', 'selfie', 'government_id', 'identity_manual']",
       "['email', 'phone']"], dtype=object)

-------------------------------------
Colonne : host_has_profile_pic
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['t', 'f'], dtype=object)

-------------------------------------
Colonne : host_identity_verified
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['t', 'f'], dtype=object)

-------------------------------------
Colonne : street
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 242
-------------------------------------

array(['Paris, Île-de-France, France', 'Paris, Ile-de-France, France',
       'Paris, IDF, France', 'Paris, France', 'Paris, IdF, France',
       'Paris, 4th arrondissement, Île-de-France, France',
       'Saint-Mandé, Île-de-France, France', 'Paris, Paris, France',
       'Paris , Île-de-France, France',
       'Paris-13E-Arrondissement, Île-de-France, France'], dtype=object)

-------------------------------------
Colonne : neighbourhood
Type : object
Valeurs manquantes : 4.4%
Nombre de valeurs uniques : 61
-------------------------------------

array(['République', 'Alésia', 'Saint-Paul - Ile Saint-Louis',
       'Le Marais', "Gare du Nord - Gare de I'Est",
       'Père Lachaise - Ménilmontant', 'Montmartre', 'Saint-Lazare',
       'Panthéon', "Place d'Italie - Quartier Chinois"], dtype=object)

-------------------------------------
Colonne : neighbourhood_cleansed
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 20
-------------------------------------

array(['Entrepôt', 'Observatoire', 'Hôtel-de-Ville', 'Opéra',
       'Ménilmontant', 'Louvre', 'Popincourt', 'Buttes-Montmartre',
       'Élysée', 'Panthéon'], dtype=object)

-------------------------------------
Colonne : neighbourhood_group_cleansed
Type : float64
Valeurs manquantes : 100.0%
Nombre de valeurs uniques : 0
-------------------------------------

array([], dtype=float64)

-------------------------------------
Colonne : city
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 132
-------------------------------------

array(['Paris', 'Paris, 4th arrondissement', 'Saint-Mandé', 'Paris ',
       'Paris-13E-Arrondissement', 'Levallois-Perret',
       'Paris-2E-Arrondissement', 'Paris 4e arrondissement', 'Vincennes',
       'Boulogne-Billancourt'], dtype=object)

-------------------------------------
Colonne : state
Type : object
Valeurs manquantes : 1.2%
Nombre de valeurs uniques : 50
-------------------------------------

array(['Île-de-France', 'Ile-de-France', 'IDF', 'IdF', 'Paris', 'FRANCE',
       'France', 'Ile de France', 'Pairs', 'Ile de france'], dtype=object)

-------------------------------------
Colonne : zipcode
Type : object
Valeurs manquantes : 1.3%
Nombre de valeurs uniques : 75
-------------------------------------

array(['75010', '75014', '75004', '75009', '75020', '75001', '75011',
       '75018', '75008', '75005'], dtype=object)

-------------------------------------
Colonne : market
Type : object
Valeurs manquantes : 0.2%
Nombre de valeurs uniques : 22
-------------------------------------

array(['Paris', 'Other (International)', 'Loire Valley', 'Toulouse',
       'Orleans', 'Marseille', 'Basque Country', 'Deauville', 'Brussels',
       'Berlin'], dtype=object)

-------------------------------------
Colonne : smart_location
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 134
-------------------------------------

array(['Paris, France', 'Paris, 4th arrondissement, France',
       'Saint-Mandé, France', 'Paris , France',
       'Paris-13E-Arrondissement, France', 'Levallois-Perret, France',
       'Paris-2E-Arrondissement, France',
       'Paris 4e arrondissement, France', 'FR, France',
       'Vincennes, France'], dtype=object)

-------------------------------------
Colonne : country_code
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['FR', 'CH'], dtype=object)

-------------------------------------
Colonne : country
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['France', 'Switzerland'], dtype=object)

-------------------------------------
Colonne : latitude
Type : float64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 59881
-------------------------------------

array([48.86993262, 48.83349369, 48.85100067, 48.85757577, 48.87464191,
       48.86527873, 48.85898545, 48.86226582, 48.86277521, 48.86743024])

-------------------------------------
Colonne : longitude
Type : float64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 59881
-------------------------------------

array([2.36251064, 2.31851792, 2.35869042, 2.35275131, 2.34341111,
       2.39326349, 2.34734722, 2.37134096, 2.37467959, 2.37523953])

-------------------------------------
Colonne : is_location_exact
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['t', 'f'], dtype=object)

-------------------------------------
Colonne : property_type
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 32
-------------------------------------

array(['Loft', 'Apartment', 'Condominium', 'Bed and breakfast', 'House',
       'Townhouse', 'Guesthouse', 'Boat', 'Guest suite', 'Tiny house'],
      dtype=object)

-------------------------------------
Colonne : room_type
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 3
-------------------------------------

array(['Entire home/apt', 'Private room', 'Shared room'], dtype=object)

-------------------------------------
Colonne : accommodates
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 17
-------------------------------------

array([ 4,  2,  3,  5,  6,  1, 14,  9,  7,  8])

-------------------------------------
Colonne : bathrooms
Type : float64
Valeurs manquantes : 0.1%
Nombre de valeurs uniques : 18
-------------------------------------

array([2. , 1. , 1.5, 2.5, 4.5, 0.5, 0. , 3. , 4. , 5. ])

-------------------------------------
Colonne : bedrooms
Type : float64
Valeurs manquantes : 0.1%
Nombre de valeurs uniques : 10
-------------------------------------

array([ 2.,  1.,  0.,  3.,  5.,  4.,  6.,  7., 10., 50.])

-------------------------------------
Colonne : beds
Type : float64
Valeurs manquantes : 0.4%
Nombre de valeurs uniques : 19
-------------------------------------

array([ 2.,  1.,  3.,  4.,  0.,  8.,  6.,  5.,  7., 10.])

-------------------------------------
Colonne : bed_type
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 5
-------------------------------------

array(['Real Bed', 'Pull-out Sofa', 'Futon', 'Couch', 'Airbed'],
      dtype=object)

-------------------------------------
Colonne : amenities
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 53706
-------------------------------------

array(['{TV,Internet,Wifi,Kitchen,Heating,Washer,Dryer,Essentials,Hangers,Iron,"Laptop friendly workspace","Hot water","Host greets you"}',
       '{Internet,Wifi,Kitchen,"Paid parking off premises","Family/kid friendly",Washer,"Smoke detector",Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Self check-in","Smart lock","Children’s books and toys","Hot water","Luggage dropoff allowed"}',
       '{TV,"Cable TV",Internet,Wifi,Kitchen,Heating,Washer,"Smoke detector","Fire extinguisher",Essentials,Shampoo,Hangers,"Hair dryer","Laptop friendly workspace","Hot water","Bed linens","Extra pillows and blankets","Long term stays allowed","Host greets you"}',
       '{TV,"Cable TV",Internet,Wifi,Kitchen,"Paid parking off premises","Buzzer/wireless intercom",Heating,"Family/kid friendly",Washer,"Smoke detector","Carbon monoxide detector",Essentials,Shampoo,"24-hour check-in",Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Hot water","Host greets you"}',
       '{TV,"Cable TV",Internet,Wifi,Kitchen,"Buzzer/wireless intercom",Heating,Washer,Essentials,Hangers,Iron,"Laptop friendly workspace"}',
       '{Internet,Wifi,Kitchen,"Washer / Dryer",Elevator,Heating,Washer,Dryer}',
       '{Internet,Wifi,Kitchen,Elevator,Heating,Essentials,"Hair dryer","translation missing: en.hosting_amenity_49","translation missing: en.hosting_amenity_50"}',
       '{TV,Internet,Wifi,Kitchen,"Paid parking off premises",Heating,"Smoke detector","First aid kit",Essentials,Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Hot water","Luggage dropoff allowed","Long term stays allowed","Host greets you"}',
       '{TV,"Cable TV",Internet,Wifi,Kitchen,Breakfast,Heating,"Family/kid friendly","Smoke detector","Carbon monoxide detector",Essentials,Shampoo,"24-hour check-in",Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Self check-in","Private entrance","Pack ’n Play/travel crib","Hot water","Host greets you"}',
       '{TV,"Cable TV",Internet,Wifi,Kitchen,Breakfast,Heating,"Smoke detector","Carbon monoxide detector","Fire extinguisher",Essentials,Shampoo,"24-hour check-in",Hangers,"Hair dryer",Iron,"Laptop friendly workspace","translation missing: en.hosting_amenity_49","translation missing: en.hosting_amenity_50","Private entrance","Hot water","Bed linens","Extra pillows and blankets",Microwave,"Coffee maker",Refrigerator,Dishwasher,"Dishes and silverware","Cooking basics",Oven,Stove,"Luggage dropoff allowed","Long term stays allowed","Host greets you"}'],
      dtype=object)

-------------------------------------
Colonne : square_feet
Type : float64
Valeurs manquantes : 97.7%
Nombre de valeurs uniques : 142
-------------------------------------

array([  0., 350., 538., 377., 603., 248., 269., 484., 560., 323.])

-------------------------------------
Colonne : price
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 587
-------------------------------------

array(['$125.00', '$75.00', '$115.00', '$99.00', '$90.00', '$70.00',
       '$135.00', '$105.00', '$80.00', '$85.00'], dtype=object)

-------------------------------------
Colonne : weekly_price
Type : object
Valeurs manquantes : 79.7%
Nombre de valeurs uniques : 769
-------------------------------------

array(['$490.00', '$600.00', '$770.00', '$560.00', '$475.00', '$425.00',
       '$539.00', '$934.00', '$900.00', '$400.00'], dtype=object)

-------------------------------------
Colonne : monthly_price
Type : object
Valeurs manquantes : 87.0%
Nombre de valeurs uniques : 839
-------------------------------------

array(['$2,000.00', '$2,200.00', '$1,480.00', '$1,300.00', '$1,000.00',
       '$1,510.00', '$3,297.00', '$3,000.00', '$2,300.00', '$1,500.00'],
      dtype=object)

-------------------------------------
Colonne : security_deposit
Type : object
Valeurs manquantes : 31.8%
Nombre de valeurs uniques : 421
-------------------------------------

array(['$0.00', '$200.00', '$500.00', '$1,500.00', '$250.00', '$400.00',
       '$800.00', '$600.00', '$1,000.00', '$80.00'], dtype=object)

-------------------------------------
Colonne : cleaning_fee
Type : object
Valeurs manquantes : 28.0%
Nombre de valeurs uniques : 184
-------------------------------------

array(['$40.00', '$50.00', '$36.00', '$60.00', '$200.00', '$20.00',
       '$35.00', '$70.00', '$25.00', '$0.00'], dtype=object)

-------------------------------------
Colonne : guests_included
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 15
-------------------------------------

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

-------------------------------------
Colonne : extra_people
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 101
-------------------------------------

array(['$0.00', '$10.00', '$45.00', '$30.00', '$4.00', '$3.00', '$13.00',
       '$29.00', '$5.00', '$25.00'], dtype=object)

-------------------------------------
Colonne : minimum_nights
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 102
-------------------------------------

array([  3,   2,  10, 180,   5,  90,  30,   1,   7,   6])

-------------------------------------
Colonne : maximum_nights
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 257
-------------------------------------

array([1125,   15,   30,   23,  365,  119,   60,  730,   90,   20])

-------------------------------------
Colonne : calendar_updated
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 77
-------------------------------------

array(['4 weeks ago', '5 days ago', '6 days ago', 'today', '2 days ago',
       '10 months ago', '3 weeks ago', 'yesterday', '7 weeks ago',
       '2 months ago'], dtype=object)

-------------------------------------
Colonne : has_availability
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 1
-------------------------------------

array(['t'], dtype=object)

-------------------------------------
Colonne : availability_30
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 31
-------------------------------------

array([12,  3,  1,  4,  0,  2,  6, 11,  8,  5])

-------------------------------------
Colonne : availability_60
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 61
-------------------------------------

array([13,  4,  6, 33, 30,  0, 26, 15, 41,  3])

-------------------------------------
Colonne : availability_90
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 91
-------------------------------------

array([13, 17, 28, 49,  4, 60,  7, 11, 51, 39])

-------------------------------------
Colonne : availability_365
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 366
-------------------------------------

array([ 39, 271, 113, 286, 164, 335, 282, 219,  61,  63])

-------------------------------------
Colonne : calendar_last_scraped
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['2018-12-08', '2018-12-07'], dtype=object)

-------------------------------------
Colonne : number_of_reviews
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 378
-------------------------------------

array([  0,   7, 148, 231,   6,   1,  17, 144, 147,  41])

-------------------------------------
Colonne : first_review
Type : object
Valeurs manquantes : 20.9%
Nombre de valeurs uniques : 2620
-------------------------------------

array(['2016-12-27', '2009-06-30', '2011-04-08', '2010-05-10',
       '2010-06-16', '2013-03-19', '2010-01-11', '2010-09-02',
       '2009-12-20', '2011-03-13'], dtype=object)

-------------------------------------
Colonne : last_review
Type : object
Valeurs manquantes : 20.9%
Nombre de valeurs uniques : 1655
-------------------------------------

array(['2018-07-27', '2018-11-21', '2018-11-19', '2015-09-14',
       '2010-06-16', '2018-12-01', '2018-11-23', '2018-11-25',
       '2016-10-02', '2016-10-01'], dtype=object)

-------------------------------------
Colonne : review_scores_rating
Type : float64
Valeurs manquantes : 22.7%
Nombre de valeurs uniques : 52
-------------------------------------

array([100.,  94.,  96.,  99.,  97.,  88.,  93.,  92.,  95.,  98.])

-------------------------------------
Colonne : review_scores_accuracy
Type : float64
Valeurs manquantes : 22.8%
Nombre de valeurs uniques : 9
-------------------------------------

array([10.,  9.,  8.,  7.,  6.,  2.,  5.,  4.,  3.])

-------------------------------------
Colonne : review_scores_cleanliness
Type : float64
Valeurs manquantes : 22.8%
Nombre de valeurs uniques : 9
-------------------------------------

array([10.,  9.,  8.,  6.,  7.,  4.,  2.,  5.,  3.])

-------------------------------------
Colonne : review_scores_checkin
Type : float64
Valeurs manquantes : 22.9%
Nombre de valeurs uniques : 9
-------------------------------------

array([10.,  9.,  8.,  6.,  7.,  5.,  2.,  4.,  3.])

-------------------------------------
Colonne : review_scores_communication
Type : float64
Valeurs manquantes : 22.8%
Nombre de valeurs uniques : 9
-------------------------------------

array([10.,  9.,  8.,  2.,  6.,  7.,  4.,  5.,  3.])

-------------------------------------
Colonne : review_scores_location
Type : float64
Valeurs manquantes : 22.9%
Nombre de valeurs uniques : 9
-------------------------------------

array([10.,  9.,  8.,  6.,  4.,  7.,  5.,  2.,  3.])

-------------------------------------
Colonne : review_scores_value
Type : float64
Valeurs manquantes : 22.9%
Nombre de valeurs uniques : 9
-------------------------------------

array([10.,  9.,  8.,  6.,  7.,  2.,  4.,  5.,  3.])

-------------------------------------
Colonne : requires_license
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['t', 'f'], dtype=object)

-------------------------------------
Colonne : license
Type : object
Valeurs manquantes : 75.7%
Nombre de valeurs uniques : 13914
-------------------------------------

array(['7510400829623', '5962', '7510500148022', '7511111100537044',
       '7511801401834', '7511300241931', '7511100262771', '7511102600669',
       '7511802269686', '7510102359633'], dtype=object)

-------------------------------------
Colonne : jurisdiction_names
Type : object
Valeurs manquantes : 1.3%
Nombre de valeurs uniques : 31
-------------------------------------

array(['{PARIS}', '{Paris}', '{"LEVALLOIS PERRET"}', '{VINCENNES}',
       '{"BOULOGNE BILLANCOURT"}', '{PANTIN}', '{"BRAS PANON"}',
       '{"LE KREMLIN BICETRE"}', '{"NEUILLY SUR SEINE"}',
       '{"ISSY LES MOULINEAUX"}'], dtype=object)

-------------------------------------
Colonne : instant_bookable
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['t', 'f'], dtype=object)

-------------------------------------
Colonne : is_business_travel_ready
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 1
-------------------------------------

array(['f'], dtype=object)

-------------------------------------
Colonne : cancellation_policy
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 6
-------------------------------------

array(['strict_14_with_grace_period', 'flexible', 'moderate',
       'super_strict_30', 'strict', 'super_strict_60'], dtype=object)

-------------------------------------
Colonne : require_guest_profile_picture
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['f', 't'], dtype=object)

-------------------------------------
Colonne : require_guest_phone_verification
Type : object
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 2
-------------------------------------

array(['f', 't'], dtype=object)

-------------------------------------
Colonne : calculated_host_listings_count
Type : int64
Valeurs manquantes : 0.0%
Nombre de valeurs uniques : 57
-------------------------------------

array([ 1,  6,  3,  2,  4,  7, 72,  5, 13, 39])

-------------------------------------
Colonne : reviews_per_month
Type : float64
Valeurs manquantes : 20.9%
Nombre de valeurs uniques : 885
-------------------------------------

array([0.29, 1.29, 2.47, 0.06, 0.01, 0.24, 1.33, 1.46, 0.38, 0.17])

# 3. Les colonnes à prendre ou à laisser

### Les colonnes à garder absolument et transformer en cas de besoin :

- Identité & localisation (cartographie, clustering, matching géospatial, itinéraires) : latitude (0% missing), longitude (0% missing), name (0,1% missing), city (0,1% missing), zipcode (1% missing), transit (36% missing), listing_url (0.01% missing)

- Type de logement & capacité : description (1% missing), property_type (0% missing), bedrooms (0.11% missing), beds (% missing), bed_type (0% missing), bathrooms (0.13% missing), accommodates (ex : accommodates=2 --> logement pour 2 personnes) (0% missing), amenities (0% missing)

- Prix : price (0% missing), cleaning_fee (27% missing), guests_included (0% missing), extra_people (0% missing)

- Règles : security_deposit (31% missing), minimum_nights (0% missing), maximum_nights (0% missing), cancellation_policy (0% missing), require_guest_profile_picture (0% missing), require_guest_phone_verification (0% missing), 

- Disponibilité : availability_30 (ex : availability_30 = 12 → 12 nuits libres sur les 30 à venir) (0% missing), availability_60 (0% missing), availability_90 (0% missing), availability_365 (0% missing)

- Avis & réputation (score) : number_of_reviews (0% missing), review_scores_rating (23% missing), reviews_per_month (21% missing), last_review (21% missing), review_scores_location (23% missing), review_scores_cleanliness (23% missing), review_scores_value (23% missing),

### Les colonnes à ignorer :

neighborhood_overview (40% missing), space (32% missing), notes (69% missing), interaction (52% missing), summary (4% missing), house_rules (52% missing), access (52% missing), host_url (0% missing), host_name (0,01% missing), host_identity_verified (0,01% missing), host_about (49% missing), host_since (0,01% missing), host_is_superhost (0,01% missing), room_type (0% missing),host_response_time (48% missing), 

host_verifications (0,01% missing), host_response_rate (48% missing), first_review (21% missing), review_scores_checkin (23% missing), review_scores_accuracy (23% missing), review_scores_communication (23% missing), calendar_updated (0% missing), has_availability (0% missing), is_location_exact (0% missing), street (0% missing), country (0% missing), country_code (0% missing), neighbourhood_cleansed (0% missing), host_id (0% missing), host_listings_count (0.01% missing), host_total_listings_count (0.01% missing), picture_url (0% missing), smart_location (0% missing), requires_license (0% missing), calculated_host_listings_count (0% missing), scrape_id (0% missing), thumbnail_url (100% missing), medium_url (100% missing), xl_picture_url (100% missing), host_acceptance_rate (100% missing), instant_bookable (0% missing), neighbourhood_group_cleansed (100% missing), host_thumbnail_url (0,01% missing), host_picture_url (0,01% missing), jurisdiction_names (1% missing), experiences_offered (0% missing), , square_feet (98% missing), host_neighbourhood (14% missing), state (1% missing), host_location (0,3% missing), market (0,2% missing), host_has_profile_pic (0,01% missing), is_business_travel_ready (0% missing), has_availability (0% missing), last_scraped (0% missing)

# 4. Nettoyer + compléter + transformer les valeurs

In [4]:
#transformer en booléen les colonnes require_guest_phone_verification (0% missing), require_guest_profile_picture (0% missing), 

BOOL_COLS = ["require_guest_phone_verification", "require_guest_profile_picture", "host_is_superhost", "host_identity_verified"]
for col in BOOL_COLS:
    if col in df_listings.columns:
        df_listings[col] = (df_listings[col].astype(str).str.lower().isin(["t", "true", "1", "yes"]))

In [5]:
#convertir review_scores_rating sur 5
df_listings["review_scores_rating"] = (pd.to_numeric(df_listings["review_scores_rating"], errors="coerce") / 20).round(2)

In [6]:
#Nettoyer + transformer en float : price (0% missing), cleaning_fee (27% missing), security_deposit (31% missing),
#extra_people (0% missing), weekly_price (79% missing), monthly_price (87% missing)

PRICE_COLS = ["price", "cleaning_fee", "security_deposit", "extra_people", "weekly_price", "monthly_price"]
for col in PRICE_COLS:
    if col in df_listings.columns:
        df_listings[col] = (df_listings[col].astype(str).str.replace(r"[^0-9.]", "", regex=True))
        df_listings[col] = pd.to_numeric(df_listings[col], errors="coerce")
        df_listings[col] = df_listings[col].astype("float").fillna(0)

In [7]:
#créer et calculer la colonne "price_level" en mode quantiles basant sur colonne "price" : 1=petit <= q1 ; q1 < 2=moyen <= q2 ; 3=confort > q2

#regarder la distribution
df_listings["price"].describe(percentiles=[0.33, 0.66])

#calculer les seuils
q1 = df_listings["price"].quantile(0.33)
q2 = df_listings["price"].quantile(0.66)
q1, q2

#créer price_level
df_listings["price_level"] = np.nan

df_listings.loc[df_listings["price"] <= q1, "price_level"] = 1
df_listings.loc[(df_listings["price"] > q1) & (df_listings["price"] <= q2), "price_level"] = 2
df_listings.loc[df_listings["price"] > q2, "price_level"] = 3

df_listings[["price_level", "price"]].head(5)

   price_level  price
0          3.0  125.0
1          2.0   75.0
2          3.0  115.0
3          3.0  115.0
4          2.0   99.0

# 5. DataFrame Final (normer les colonnes afin de mapper avec les autres datasets dans streamlit)

19 colonnes normées UX streamlit : source_id, source, type, raw_type, url, lat, lon, name, address, postal_code, city, region, country, snippet, rating, review_count, price_level, max_people, distance_km

In [12]:
# Alléger le df --> Filtre qualité (garder seulement avec rating + min avis)
#df_listings = df_listings[df_listings["review_scores_rating"].notna() & (df_listings["number_of_reviews"] >= 3)]

# Alléger le df --> tronquer la colonne "description"
#df_listings["description_tron"] = (df_listings["description"].fillna("").astype(str).str.replace(r"\s+", " ", regex=True).str.strip().str.slice(0, 350))

# Garder uniquement les colonnes utiles
cols_keep = ["id", "listing_url", "name", "city", "zipcode", "state", "country", "summary",
             "latitude", "longitude", "review_scores_rating", "number_of_reviews", "accommodates", "price", "price_level"]

df_airbnb_clean = df_listings[cols_keep].copy()

# Créer les colonnes standards et les colonnes manquantes pour UX design
df_airbnb_clean["source"] = "AirBnb-Paris"
df_airbnb_clean["type"] = "Airbnb"
df_airbnb_clean["distance_km"] = np.nan
df_airbnb_clean["address"] = np.nan

# Normaliser / renommer
rename_map={"id": "source_id",
            "listing_url": "url",
            "latitude": "lat",
            "longitude": "lon",
            "zipcode": "postal_code",
            "state": "region",
            "review_scores_rating": "rating",
            "number_of_reviews": "review_count",
            "accommodates": "max_people",
            "summary" : "snippet"}
df_airbnb_clean_norm = df_airbnb_clean.rename(columns = rename_map, errors="ignore")

# réordonner les colonnes UX
UX_COLUMNS = ["source_id", "source", "type", "url", "lat", "lon",
              "name", "address", "postal_code", "city", "region", "country",
              "snippet", "rating", "review_count", "price_level", "max_people", "distance_km", "price"]

for col in UX_COLUMNS:
    if col not in df_airbnb_clean_norm.columns:
        df_airbnb_clean_norm[col] = None
        
df_airbnb_clean_normux = df_airbnb_clean_norm[UX_COLUMNS]

#sauvegarder les changements
df_airbnb_Paris = df_airbnb_clean_normux.copy()

# Export parquet final (un seul fichier)
df_airbnb_Paris.to_parquet("df_airbnb_Paris.parquet", index=False, engine="pyarrow", compression="zstd", compression_level=9)

#vérifier
display(df_airbnb_Paris.head(3))
display(df_airbnb_Paris.info())

,source_id,source,type,url,lat,lon,name,address,postal_code,city,region,country,snippet,rating,review_count,price_level,max_people,distance_km,price
0,2577,AirBnb-Paris,Airbnb,https://www.airbnb.com/rooms/2577,48.869933,2.362511,Loft for 4 by Canal Saint Martin,NaN,75010,Paris,Île-de-France,France,"100 m2 loft (1100 sq feet) with high ceiling, ...",NaN,0,3.0,4,NaN,125.0
1,3109,AirBnb-Paris,Airbnb,https://www.airbnb.com/rooms/3109,48.833494,2.318518,zen and calm,NaN,75014,Paris,Île-de-France,France,Appartement très calme de 50M2 Belle lumière D...,5.0,7,2.0,2,NaN,75.0
2,5396,AirBnb-Paris,Airbnb,https://www.airbnb.com/rooms/5396,48.851001,2.358690,Explore the heart of old Paris,NaN,75004,Paris,Ile-de-France,France,"Cozy, well-appointed and graciously designed s...",4.7,148,3.0,2,NaN,115.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59881 entries, 0 to 59880
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   source_id     59881 non-null  int64
 1   source        59881 non-null  object
 2   type          59881 non-null  object
 3   url           59881 non-null  object
 4   lat           59881 non-null  float64
 5   lon           59881 non-null  float64
 6   name          59807 non-null  object
 7   address       0 non-null      float64
 8   postal_code   59084 non-null  object
 9   city          59860 non-null  object
 10  region        59151 non-null  object
 11  country       59881 non-null  object
 12  snippet       57524 non-null  object
 13  rating        46289 non-null  float64
 14  review_count  59881 non-null  int64
 15  price_level   59881 non-null  float64
 16  max_people    59881 non-null  int64
 17  distance_km   0 non-null      float64
 18  price         59881 non-null  float64
dtypes: float64(7), int64(3), object(9)
memory usage: 8.7+ MB

None